var LANG_KEY='voicenote_lang',LANGS=['en','fr','de','es','it','zh'];
var T={
'Home':{fr:'Accueil',de:'Start',es:'Inicio',it:'Home',zh:'首页'},
'Pricing':{fr:'Tarifs',de:'Preise',es:'Precios',it:'Prezzi',zh:'定价'},
'Download':{fr:'Telecharger',de:'Download',es:'Descargar',it:'Scarica',zh:'下载'},
'Contact':{fr:'Contact',de:'Kontakt',es:'Contacto',it:'Contatto',zh:'联系'},
'Try Free':{fr:'Essai Gratuit',de:'Testen',es:'Probar',it:'Prova',zh:'免费试用'},
// Hero
'Your AI Voice Alchemist':{fr:'Votre Alchimiste Vocal IA',de:'Ihr KI-Sprachalchemist',es:'Tu Alquimista de Voz IA',it:'Il Tuo Alchimista Vocale IA',zh:'你的 AI 语音炼金师'},
'Turn messy thoughts':{fr:'Pensees brouillonnes',de:'Chaotische Gedanken',es:'Pensamientos',it:'Pensieri confusi',zh:'将混乱的想法'},
'into structured text':{fr:'en texte structure',de:'in Text',es:'en texto',it:'in testo',zh:'变成清晰的文字'},
'Stop worrying about filler words, pauses, or grammar. Just speak naturally — VoiceNote\'s AI instantly rewrites your voice for any context.':{fr:'Arretez de vous soucier. Parlez, VoiceNote reecrit.',de:'Sorgen um Pausen? Sprechen Sie, VoiceNote schreibt um.',es:'No te preocupes. Habla, VoiceNote reescribe.',it:'Non preoccuparti. Parla, VoiceNote riscrive.',zh:'别再担心语气词。自然说，VoiceNote 即刻重写。'},
// Sections
'Simple & Fast':{fr:'Simple et Rapide',de:'Einfach & Schnell',es:'Simple y Rapido',it:'Semplice e Veloce',zh:'简单快速'},
'AI Smart Styles':{fr:'Styles IA',de:'KI Stile',es:'Estilos IA',it:'Stili IA',zh:'AI 智能风格'},
'46 Languages':{fr:'46 Langues',de:'46 Sprachen',es:'46 Idiomas',it:'46 Lingue',zh:'46 种语言'},
'Built for Thinkers':{fr:'Pour les Penseurs',de:'Fur Denker',es:'Para Pensadores',it:'Per Pensatori',zh:'为思考者而生'},
// How it works
'From voice to perfect text in 3 steps':{fr:'De la voix au texte parfait en 3 etapes',de:'Von Sprache zu perfektem Text in 3 Schritten',es:'De voz a texto perfecto en 3 pasos',it:'Dalla voce al testo perfetto in 3 passi',zh:'从语音到完美文字只需三步'},
'Speak Freely':{fr:'Parlez Librement',de:'Frei Sprechen',es:'Habla Libremente',it:'Parla Liberamente',zh:'自由说'},
'Tap the mic and talk without filtering. Um\'s, ah\'s, and pauses? Our AI ignores them.':{fr:'Appuyez et parlez sans filtre. Les hesitations? Notre IA les ignore.',de:'Tippen Sie und sprechen Sie. Unsere KI ignoriert Pausen.',es:'Toca y habla sin filtrar. Nuestra IA ignora las pausas.',it:'Tocca e parla senza filtri. La nostra IA ignora le pause.',zh:'点击麦克风自由说。语气词和停顿？AI 会忽略。'},
'Choose Your Style':{fr:'Choisissez votre style',de:'Stil wahlen',es:'Elige tu estilo',it:'Scegli lo stile',zh:'选择风格'},
'Select your context. Need an email, a tweet, or a structured summary?':{fr:'Choisissez votre contexte. Un email, un tweet ou un resume structure?',de:'Kontext wahlen. E-Mail, Tweet oder Zusammenfassung?',es:'Elige contexto. Email, tweet o resumen?',it:'Scegli il contesto. Email, tweet o riassunto?',zh:'选择场景。邮件、推文还是摘要？'},
'Ready to Use':{fr:'Pret a l\'emploi',de:'Einsatzbereit',es:'Listo para usar',it:'Pronto all\'uso',zh:'立即可用'},
'Get beautifully polished, ready-to-share text in seconds.':{fr:'Obtenez un texte parfait, pret a partager en quelques secondes.',de:'Erhalten Sie perfekt formatierten Text in Sekunden.',es:'Obten texto pulido listo para compartir en segundos.',it:'Ottieni testo perfetto, pronto da condividere in pochi secondi.',zh:'秒速获得润色精美的文字，立即可分享。'},
// Hero demo card
'Voice input':{fr:'Entree vocale',de:'Spracheingabe',es:'Entrada de voz',it:'Ingresso vocale',zh:'语音输入'},
'AI polished':{fr:'Peaufine par IA',de:'KI-verfeinert',es:'Pulido por IA',it:'Perfezionato dall\'IA',zh:'AI 润色后'},
'Download on the':{fr:'Telecharger sur l\'',de:'Laden im',es:'Descargar en',it:'Scarica su',zh:'在 '},
'dl.btn':{fr:'Telecharger sur l\'App Store',de:'Im App Store laden',es:'Descargar en App Store',it:'Scarica su App Store',zh:'在 App Store 下载'},
'App Store':{fr:'App Store',de:'App Store',es:'App Store',it:'App Store',zh:'App Store'},
// Smart Styles
'VOICE INPUT':{fr:'ENTREE VOCALE',de:'SPRACHEINGABE',es:'ENTRADA DE VOZ',it:'INGRESSO VOCALE',zh:'语音输入'},
'Plain & Direct':{fr:'Clair & Direct',de:'Klar & Direkt',es:'Claro & Directo',it:'Chiaro & Diretto',zh:'简洁直接'},
'Professional Email':{fr:'Email Professionnel',de:'E-Mail',es:'Email Profesional',it:'Email Professionale',zh:'正式邮件'},
'Key Takeaways':{fr:'Points Cles',de:'Kernpunkte',es:'Puntos Clave',it:'Punti Chiave',zh:'要点总结'},
'Casual / Slack':{fr:'Decontracte',de:'Locker',es:'Informal',it:'Informale',zh:'随意聊天'},
// Pricing
'Free':{fr:'Gratuit',de:'Kostenlos',es:'Gratis',it:'Gratuito',zh:'免费版'},
'Prime':{fr:'Premium',de:'Prime',es:'Premium',it:'Premium',zh:'高级版'},
'Start your free trial':{fr:'Essai gratuit',de:'Testversion',es:'Prueba gratuita',it:'Prova gratuita',zh:'开始免费试用'},
'Try Free Now':{fr:'Essayer',de:'Jetzt testen',es:'Probar ahora',it:'Prova ora',zh:'立即试用'},
'10 free notes':{fr:'10 notes gratuites',de:'10 Notizen',es:'10 notas gratis',it:'10 note gratis',zh:'10 条免费笔记'},
'2 min per recording':{fr:'2 min/enreg',de:'2 Min/Aufn',es:'2 min/grab',it:'2 min/reg',zh:'2 分钟/条'},
'Standard AI polish':{fr:'Polissage standard',de:'KI-Politur',es:'Pulido estandar',it:'Perfezionamento',zh:'标准 AI 润色'},
'46 languages':{fr:'46 langues',de:'46 Sprachen',es:'46 idiomas',it:'46 lingue',zh:'46 种语言'},
'No credit card needed':{fr:'Sans CB',de:'Keine Karte',es:'Sin tarjeta',it:'Nessuna carta',zh:'无需信用卡'},
'Everything in Free, plus unlimited':{fr:'Tout Free en illimite',de:'Alles von Free',es:'Todo Free ilimitado',it:'Tutto Free illimitato',zh:'Free 全部 + 无限'},
'Download & Try Free':{fr:'Telecharger et essayer',de:'Download & testen',es:'Descargar y probar',it:'Scarica e prova',zh:'下载试用'},
'Unlimited notes':{fr:'Notes illimitees',de:'Unbegrenzt',es:'Ilimitadas',it:'Illimitate',zh:'无限笔记'},
'15 min per recording':{fr:'15 min/enreg',de:'15 Min/Aufn',es:'15 min/grab',it:'15 min/reg',zh:'15 分钟/条'},
'Advanced AI + all styles':{fr:'IA avancee + styles',de:'KI + alle Stile',es:'IA avanzada + estilos',it:'IA avanzata + stili',zh:'高级 AI + 全风格'},
'Download on the App Store':{fr:'Telecharger',de:'Laden',es:'Descargar',it:'Scarica',zh:'在 App Store 下载'},
'Scan to download':{fr:'Scanner',de:'Scannen',es:'Escanear',it:'Scansiona',zh:'扫码下载'},
'All rights reserved.':{fr:'Tous droits reserves.',de:'Alle Rechte vorbehalten.',es:'Todos los derechos reservados.',it:'Tutti i diritti riservati.',zh:'保留所有权利。'},
'If you have questions about this Privacy Policy, please contact us at support@voicenote.uk.':{fr:'Questions : support@voicenote.uk.',de:'Fragen: support@voicenote.uk.',es:'Preguntas: support@voicenote.uk.',it:'Domande: support@voicenote.uk.',zh:'隐私政策问题：support@voicenote.uk。'},
'If you have questions about this Privacy Policy, please contact us at ':{fr:'Questions : ',de:'Fragen: ',es:'Preguntas: ',it:'Domande: ',zh:'若您对本隐私政策有疑问，可通过邮箱 '},
'.':{fr:'.',de:'.',es:'.',it:'.',zh:' 联系我们。'},
'For questions about these Terms, contact us at ':{fr:'Questions sur ces conditions : ',de:'Fragen zu diesen Bedingungen: ',es:'Preguntas sobre estos terminos: ',it:'Domande su questi termini: ',zh:'条款问题请联系：'},
'If you have questions about our Cookie Policy, contact us at ':{fr:'Questions sur les cookies : ',de:'Fragen zu Cookies: ',es:'Preguntas sobre cookies: ',it:'Domande sui cookie: ',zh:'Cookie 政策问题请联系：'},
'All rights reserved.':{fr:'Tous droits reserves.',de:'Alle Rechte vorbehalten.',es:'Todos los derechos reservados.',it:'Tutti i diritti riservati.',zh:'保留所有权利。'},
'Privacy':{fr:'Confidentialite',de:'Datenschutz',es:'Privacidad',it:'Privacy',zh:'隐私'},
'Privacy ':{fr:'Confidentialite ',de:'Datenschutz ',es:'Privacidad ',it:'Privacy ',zh:'隐私'},
'Service':{fr:'Service',de:'Service',es:'Servicio',it:'Servizio',zh:'条款'},
'Termination':{fr:'Resiliation',de:'Kundigung',es:'Terminacion',it:'Cessazione',zh:'终止'},
'7. Termination':{fr:'7. Resiliation',de:'7. Kundigung',es:'7. Terminacion',it:'7. Cessazione',zh:'7. 终止'},
'7. ':{fr:'7. ',de:'7. ',es:'7. ',it:'7. ',zh:'7. '},
'Terms of':{fr:'Conditions d',de:'Nutzungs',es:'Terminos de',it:'Termini di',zh:'服务'},
'Terms ':{fr:'Conditions ',de:'Nutzungsbedingungen ',es:'Terminos ',it:'Termini ',zh:'服务条款 '},
'Terms':{fr:'Conditions',de:'Nutzungsbedingungen',es:'Terminos',it:'Termini',zh:'服务条款'},
'Terms ':{fr:'Conditions ',de:'Nutzungsbedingungen ',es:'Terminos ',it:'Termini ',zh:'服务条款'},
'Policy':{fr:'Politique',de:'Richtlinie',es:'Politica',it:'Politica',zh:'政策'},
'Policy ':{fr:'Politique ',de:'Richtlinie ',es:'Politica ',it:'Politica ',zh:'政策 '},
// Demo card texts
'This product converts voice into text in real time, using AI to remove filler words, fix grammar, and restructure sentences for clarity.':{fr:'Ce produit convertit la voix en texte en temps reel, avec l\'IA pour supprimer les hesitations.',de:'Dieses Produkt wandelt Sprache in Echtzeit in Text um.',es:'Este producto convierte voz en texto en tiempo real.',it:'Questo prodotto converte la voce in testo in tempo reale.',zh:'这个产品将语音实时转换为文字，用 AI 去除冗余、修正语法、优化句子。'},
'Dictate once, rewrite for any platform. Watch how VoiceNote transforms the same voice input into different formats:':{fr:'Dictez une fois, reecrivez pour chaque plateforme. Regardez VoiceNote transformer :',de:'Einmal diktieren, fur jede Plattform umschreiben:',es:'Dicta una vez, reescribe para cada plataforma:',it:'Detta una volta, riscrivi per ogni piattaforma:',zh:'说一次，为任何平台重写。看看 VoiceNote 如何转化：'},
'Um, so basically I think we should consider maybe extending the deadline for the project because, you know, like, we\'re still waiting on some feedback from the client and the design team hasn\'t finished their revisions yet and honestly we need more time to make it, like, actually good instead of rushing it out...':{fr:'Euh, donc je pense qu\'on devrait prolonger le delai d\'une semaine, parce qu\'on attend des retours client...',de:'Ah, also ich denke wir sollten die Frist um eine Woche verlangern, weil wir noch auf Feedback warten...',es:'Eh, creo que deberiamos extender el plazo una semana, porque esperamos comentarios del cliente...',it:'Ehm, penso che dovremmo estendere la scadenza di una settimana, perche aspettiamo feedback...',zh:'呃，我觉得应该把截止日期延期一周，因为还在等客户反馈，设计团队也没完成修改...'},
'We need to extend the project deadline by one week due to delayed client feedback and required design revisions.':{fr:'Nous devons prolonger le delai d\'une semaine en raison du retard des retours clients.',de:'Wir mussen die Frist um eine Woche verlangern.',es:'Necesitamos extender el plazo una semana.',it:'Dobbiamo estendere la scadenza di una settimana.',zh:'由于客户反馈延迟，我们需要延长截止日期一周。'},
'I propose extending the project deadline due to outstanding client feedback and ongoing design revisions. Additional time will ensure we deliver work that meets our quality standards.':{fr:'Je propose de prolonger le delai d\'une semaine en raison des retours clients en attente.',de:'Ich schlage vor, die Frist um eine Woche zu verlangern.',es:'Propongo extender el plazo una semana por comentarios pendientes.',it:'Propongo di estendere la scadenza di una settimana per feedback in sospeso.',zh:'由于客户反馈和设计修改尚未完成，建议延期一周。'},
'Extend project deadline by 7 days':{fr:'Prolonger le delai de 7 jours',de:'Frist um 7 Tage verlangern',es:'Extender plazo 7 dias',it:'Estendere scadenza 7 giorni',zh:'延期一周'},
'Awaiting final client feedback':{fr:'En attente du feedback client',de:'Warten auf Kundenfeedback',es:'Esperando comentarios del cliente',it:'In attesa feedback cliente',zh:'等待客户最终反馈'},
'Conduct design revisions upon receipt':{fr:'Effectuer les revisions a reception',de:'Design-Uberarbeitungen nach Erhalt',es:'Realizar revisiones al recibir',it:'Effettuare revisioni al ricevimento',zh:'收到后进行设计修改'},
'Hey team! Let\'s push the deadline back a week. Still waiting on the client, plus it gives us some breathing room for design tweaks.':{fr:'He l\'equipe! Repoussons la date d\'une semaine.',de:'Hey Team! Verschieben wir die Frist um eine Woche.',es:'Oye equipo! Aplacemos la fecha una semana.',it:'Ehi team! Rimandiamo la scadenza di una settimana.',zh:'哈喽小伙伴们，截止日期推迟一周吧。'},
// Section fragments
'From voice to perfect text ':{fr:'De la voix au texte parfait ',de:'Von Sprache zu perfektem Text ',es:'De voz a texto perfecto ',it:'Dalla voce al testo perfetto ',zh:'从语音到完美文字 '},
'in 3 steps':{fr:'en 3 etapes',de:'in 3 Schritten',es:'en 3 pasos',it:'in 3 passi',zh:'只需三步'},
'One voice note, ':{fr:'Une note vocale, ',de:'Eine Notiz, ',es:'Una nota, ',it:'Una nota, ',zh:'一条语音，'},
'endless possibilities':{fr:'possibilites infinies',de:'endlose Moglichkeiten',es:'infinitas posibilidades',it:'infinite possibilita',zh:'无限可能'},
'Speak your language,':{fr:'Parlez votre langue,',de:'Sprechen Sie Ihre Sprache,',es:'Habla tu idioma,',it:'Parla la tua lingua,',zh:'用你的语言说，'},
'Speak your language, ':{fr:'Parlez votre langue, ',de:'Sprechen Sie Ihre Sprache, ',es:'Habla tu idioma, ',it:'Parla la tua lingua, ',zh:'用你的语言说，'},
'write in any language':{fr:'ecrivez dans toute langue',de:'schreiben in jeder Sprache',es:'escribe en cualquier idioma',it:'scrivi in qualsiasi lingua',zh:'用任何语言写'},
'For minds that move':{fr:'Pour les esprits',de:'Fur Kopfe',es:'Mentes que van',it:'Menti che vanno',zh:'为思考'},
'For minds that move ':{fr:'Pour les esprits ',de:'Fur Kopfe ',es:'Mentes que van ',it:'Menti che vanno ',zh:'为思考 '},
'faster than fingers':{fr:'plus rapides que les doigts',de:'schneller als Finger',es:'mas rapido que los dedos',it:'piu veloci delle dita',zh:'比打字更快的人'},
'Ready to ':{fr:'Pret a ',de:'Bereit zum ',es:'Listo para ',it:'Pronto per ',zh:'准备好'},'Ready to':{fr:'Pret a',de:'Bereit zum',es:'Listo para',it:'Pronto per',zh:'准备好'},
'upgrade your workflow':{fr:'ameliorer votre flux?',de:'Upgrade Ihres Workflows?',es:'mejorar tu flujo?',it:'migliorare il tuo flusso?',zh:'升级工作流了吗？'},
'Um... so I think this product idea is really good because... like, it helps people just talk and get text...':{fr:'Euh... donc je pense que ce produit est vraiment bien parce que... genre, il aide les gens a parler et obtenir du texte...',de:'Ah... also ich denke diese Produktidee ist wirklich gut weil... es hilft Leuten einfach zu reden und Text zu bekommen...',es:'Eh... creo que esta idea de producto es muy buena porque... ayuda a la gente a hablar y obtener texto...',it:'Um... quindi penso che questa idea di prodotto sia davvero buona perche... aiuta le persone a parlare e ottenere testo...',zh:'呃...我觉得这个产品想法很好因为...可以帮助大家说话直接变成文字...'},
'Um, so basically I think we should consider maybe extending the deadline for the project because, you know, like, we\'re still waiting on some feedback from the client and the design team hasn\'t finished their revisions yet and honestly we need more time to make it, like, actually good instead of rushing it out...':{fr:'Euh, donc je pense qu\'on devrait prolonger le delai d\'une semaine, parce qu\'on attend encore des retours du client et l\'equipe design n\'a pas fini...',de:'Ah, also ich denke, wir sollten die Frist um eine Woche verlangern, weil wir noch auf Feedback vom Kunden warten...',es:'Eh, creo que deberiamos extender el plazo una semana, porque todavia esperamos comentarios del cliente...',it:'Ehm, penso che dovremmo estendere la scadenza di una settimana, perche stiamo ancora aspettando feedback dal cliente...',zh:'呃，所以我觉得我们应该考虑延期一周，因为你知道的，我们还在等客户的反馈，设计团队也还没完成修改，说实话我们需要更多时间来把它做好，而不是匆忙交差...'},
'This product converts voice into text in real time, using AI to remove filler words, fix grammar, and restructure sentences for clarity.':{fr:'Ce produit convertit la voix en texte en temps reel, en utilisant l\'IA pour supprimer les hesitations, corriger la grammaire et restructurer les phrases.',de:'Dieses Produkt wandelt Sprache in Echtzeit in Text um und nutzt KI, um Fullworter zu entfernen, Grammatik zu korrigieren und Satze zu strukturieren.',es:'Este producto convierte voz en texto en tiempo real, usando IA para eliminar muletillas, corregir gramatica y reestructurar oraciones.',it:'Questo prodotto converte la voce in testo in tempo reale, usando l\'IA per rimuovere parole di riempimento, correggere la grammatica e ristrutturare le frasi.',zh:'这个产品将语音实时转换为文字，用 AI 去除冗余词汇，修正语法，优化句子结构。'},
// Comparison
'Compare':{fr:'Comparer',de:'Vergleichen',es:'Comparar',it:'Confronta',zh:'对比'},
'Feature':{fr:'Fonction',de:'Funktion',es:'Funcion',it:'Funzione',zh:'功能'},
'Notes':{fr:'Notes',de:'Notizen',es:'Notas',it:'Note',zh:'笔记数'},
'Recording length':{fr:'Duree',de:'Aufnahmelange',es:'Duracion',it:'Durata',zh:'录音时长'},
'AI polish quality':{fr:'Qualite IA',de:'KI-Qualitat',es:'Calidad IA',it:'Qualita IA',zh:'AI 润色'},
'AI writing styles':{fr:'Styles IA',de:'KI-Stile',es:'Estilos IA',it:'Stili IA',zh:'AI 风格'},
'History':{fr:'Historique',de:'Verlauf',es:'Historial',it:'Cronologia',zh:'历史'},
'Support':{fr:'Support',de:'Support',es:'Soporte',it:'Supporto',zh:'支持'},
'Standard':{fr:'Standard',de:'Standard',es:'Estandar',it:'Standard',zh:'标准'},
'Advanced':{fr:'Avance',de:'Erweitert',es:'Avanzado',it:'Avanzato',zh:'高级'},
'All styles':{fr:'Tous',de:'Alle',es:'Todos',it:'Tutti',zh:'全部'},
'3 styles':{fr:'3 styles',de:'3 Stile',es:'3 estilos',it:'3 stili',zh:'3 种'},
'15 min':{fr:'15 min',de:'15 Min',es:'15 min',it:'15 min',zh:'15 分钟'},
'2 min':{fr:'2 min',de:'2 Min',es:'2 min',it:'2 min',zh:'2 分钟'},
'First 10':{fr:'10 premieres',de:'Erste 10',es:'Primeras 10',it:'Prime 10',zh:'前 10 条'},
'Unlimited':{fr:'Illimite',de:'Unbegrenzt',es:'Ilimitado',it:'Illimitato',zh:'无限'},
'Forever':{fr:'Pour toujours',de:'Fur immer',es:'Para siempre',it:'Per sempre',zh:'永久'},
'7 days':{fr:'7 jours',de:'7 Tage',es:'7 dias',it:'7 giorni',zh:'7 天'},
'1 year':{fr:'1 an',de:'1 Jahr',es:'1 ano',it:'1 anno',zh:'1 年'},
// Users
'Students':{fr:'Etudiants',de:'Studenten',es:'Estudiantes',it:'Studenti',zh:'学生'},
'Busy Parents':{fr:'Parents Occupes',de:'Eltern',es:'Padres Ocupados',it:'Genitori',zh:'忙碌的父母'},
'Writers & Creators':{fr:'Ecrivains',de:'Autoren',es:'Escritores',it:'Scrittori',zh:'作家与创作者'},
'Professionals & Executives':{fr:'Professionnels',de:'Profis',es:'Profesionales',it:'Professionisti',zh:'职场人士'},
'Thinkers & Ideators':{fr:'Penseurs',de:'Denker',es:'Pensadores',it:'Pensatori',zh:'思考者'},
'Entrepreneurs & Ideators':{fr:'Entrepreneurs',de:'Unternehmer',es:'Emprendedores',it:'Imprenditori',zh:'创业者'},
'Journal Keepers & Thinkers':{fr:'Journaliers',de:'Journal Schreiber',es:'Diarios',it:'Diario',zh:'日记爱好者'},
// Who It\'s For descriptions
'Dictate first drafts effortlessly. Never stare at a blank page again.':{fr:'Dictez vos brouillons sans effort.',de:'Diktieren Sie Entwurfe muhlos.',es:'Dicta borradores sin esfuerzo.',it:'Detta bozze senza sforzo.',zh:'轻松口述初稿，告别空白页。'},
'Turn walking thoughts into polished messages, emails, and memos on the go.':{fr:'Transformez vos pensees en messages soignes.',de:'Gedanken in Nachrichten verwandeln.',es:'Convierte pensamientos en mensajes.',it:'Trasforma pensieri in messaggi.',zh:'把随想变成精致的消息和邮件。'},
'Transcribe lectures, organise study notes, and brainstorm essays hands-free.':{fr:'Transcrivez les cours, organisez vos notes.',de:'Vorlesungen transkribieren, Notizen organisieren.',es:'Transcribe clases, organiza apuntes.',it:'Trascrivi lezioni, organizza appunti.',zh:'免提转录课程，整理笔记。'},
'Capture chaotic brainstorming sessions and instantly structure them into action plans.':{fr:'Structurez vos brainstormings en plans daction.',de:'Brainstorming in Aktionsplane umwandeln.',es:'Estructura ideas en planes de accion.',it:'Struttura il brainstorming in piani d\'azione.',zh:'把头脑风暴变成行动计划。'},
'Reflect out loud. Document your day with zero friction and clear insights.':{fr:'Reflechissez a voix haute. Documentez votre journee.',de:'Laut reflektieren. Dokumentieren Sie Ihren Tag.',es:'Reflexiona en voz alta. Documenta tu dia.',it:'Rifletti ad alta voce. Documenta la tua giornata.',zh:'用语音记录每一天，零摩擦，更清晰。'},
'Capture ideas while cooking, driving, or chasing the kids. Totally hands-free.':{fr:'Capturez des idees en cuisinant ou conduisant.',de:'Ideen beim Kochen oder Fahren festhalten.',es:'Captura ideas mientras cocinas o conduces.',it:'Cattura idee mentre cucini o guidi.',zh:'做饭开车带娃时捕捉灵感，完全免提。'},
// Fragmented headings
'One voice note,':{fr:'Une note vocale,',de:'Eine Notiz,',es:'Una nota,',it:'Una nota,',zh:'一条语音，'},
'Ready to ':{fr:'Pret a ',de:'Bereit zum ',es:'Listo para ',it:'Pronto per ',zh:'准备好'},'Ready to':{fr:'Pret a',de:'Bereit zum',es:'Listo para',it:'Pronto per',zh:'准备好'},
'upgrade your workflow?':{fr:'ameliorer votre flux?',de:'Upgrade Ihres Workflows?',es:'mejorar tu flujo?',it:'migliorare il tuo flusso?',zh:'升级工作流了吗？'},
'For minds that move':{fr:'Pour les esprits',de:'Fur Kopfe die',es:'Mentes que van',it:'Menti che vanno',zh:'为思考'},
'No matter your workflow, VoiceNote turns your spoken thoughts into action.':{fr:'VoiceNote transforme vos pensees en action.',de:'VoiceNote macht Gedanken zu Aktion.',es:'VoiceNote convierte pensamientos en accion.',it:'VoiceNote trasforma pensieri in azione.',zh:'VoiceNote 把你的想法变成行动。'},
'VoiceNote transcribes and polishes in 46 languages, right out of the box.':{fr:'VoiceNote transcrit en 46 langues.',de:'VoiceNote in 46 Sprachen.',es:'VoiceNote en 46 idiomas.',it:'VoiceNote in 46 lingue.',zh:'VoiceNote 支持 46 种语言。'},
// More fragments
// Smart Styles output examples
'Dictate once, rewrite for any platform. Watch how VoiceNote transforms the same voice input into different formats:':{fr:'Dictez une fois, reecrivez pour chaque plateforme. Regardez VoiceNote transformer la meme entree vocale en differents formats :',de:'Einmal diktieren, fur jede Plattform umschreiben. Sehen Sie, wie VoiceNote dieselbe Eingabe in verschiedene Formate umwandelt:',es:'Dicta una vez, reescribe para cada plataforma. Mira como VoiceNote transforma la misma entrada de voz en diferentes formatos:',it:'Detta una volta, riscrivi per ogni piattaforma. Guarda come VoiceNote trasforma lo stesso input vocale in diversi formati:',zh:'说一次，为任何平台重写。看看 VoiceNote 如何将同一语音转化为不同格式：'},
'We need to extend the project deadline by one week due to delayed client feedback and required design revisions.':{fr:'Nous devons prolonger le delai du projet d\'une semaine en raison du retard des retours clients et des revisions de conception necessaires.',de:'Wir mussen die Projektfrist um eine Woche verlangern, da Kundenfeedback und Designuberarbeitungen ausstehen.',es:'Necesitamos extender el plazo del proyecto una semana debido al retraso en los comentarios del cliente y las revisiones de diseno requeridas.',it:'Dobbiamo estendere la scadenza del progetto di una settimana a causa del ritardo nel feedback del cliente e delle revisioni di design necessarie.',zh:'由于客户反馈延迟和设计修改需要，我们需要将项目截止日期延长一周。'},
'I propose extending the project deadline due to outstanding client feedback and ongoing design revisions. Additional time will ensure we deliver work that meets our quality standards.':{fr:'Je propose de prolonger le delai d\'une semaine. Ce temps supplementaire garantira la qualite.',de:'Ich schlage vor, die Frist um eine Woche zu verlangern. Zusatzliche Zeit sichert Qualitat.',es:'Propongo extender el plazo una semana. El tiempo adicional garantizara calidad.',it:'Propongo di estendere la scadenza di una settimana. Tempo aggiuntivo garantira qualita.',zh:'由于客户反馈和设计修改尚未完成，我建议延期一周。额外时间将确保我们交付符合质量标准的工作。'},
'Hey team! Let\'s push the deadline back a week. Still waiting on the client, plus it gives us some breathing room for design tweaks.':{fr:'He l\'equipe! Repoussons la date d\'une semaine. On attend encore le client, et ca nous laisse de la marge pour les ajustements design.',de:'Hey Team! Verschieben wir die Frist um eine Woche. Warten noch auf den Kunden, und es gibt uns Luft fur Design-Anpassungen.',es:'Oye equipo! Aplacemos la fecha una semana. Seguimos esperando al cliente, y nos da margen para ajustes de diseno.',it:'Ehi team! Rimandiamo la scadenza di una settimana. Aspettiamo ancora il cliente, e ci da respiro per le modifiche al design.',zh:'哈喽小伙伴们，截止日期推迟一周吧。还在等客户反馈，也给我们留点设计调整的空间。'},
'Hey team! Let\'s push the deadline back a week. Still waiting on the client, plus it gives us some breathing room for design tweaks. \u{1F64C}':{fr:'He l\'equipe! Repoussons la date d\'une semaine. On attend encore le client, et ca nous laisse de la marge pour les ajustements design. \u{1F64C}',de:'Hey Team! Verschieben wir die Frist um eine Woche. Warten noch auf den Kunden, und es gibt uns Luft fur Design-Anpassungen. \u{1F64C}',es:'Oye equipo! Aplacemos la fecha una semana. Seguimos esperando al cliente, y nos da margen para ajustes de diseno. \u{1F64C}',it:'Ehi team! Rimandiamo la scadenza di una settimana. Aspettiamo ancora il cliente, e ci da respiro per le modifiche al design. \u{1F64C}',zh:'哈喽小伙伴们，截止日期推迟一周吧。还在等客户反馈，也给我们留点设计调整的空间。 \u{1F64C}'},
'Extend project deadline by 7 days':{fr:'Prolonger le delai de 7 jours',de:'Frist um 7 Tage verlangern',es:'Extender el plazo 7 dias',it:'Estendere la scadenza di 7 giorni',zh:'延期一周'},
'Awaiting final client feedback':{fr:'En attente du feedback final du client',de:'Warten auf finales Kundenfeedback',es:'Esperando comentarios finales del cliente',it:'In attesa del feedback finale del cliente',zh:'等待客户最终反馈'},
'Conduct design revisions upon receipt':{fr:'Effectuer les revisions de conception a reception',de:'Design-Uberarbeitungen nach Erhalt durchfuhren',es:'Realizar revisiones de diseno al recibir',it:'Effettuare revisioni di design al ricevimento',zh:'收到反馈后进行设计修改'},
'Subject: ':{fr:'Objet : ',de:'Betreff: ',es:'Asunto: ',it:'Oggetto: ',zh:'主题：'},
'Project Timeline Extension':{fr:'Prolongation du delai',de:'Fristverlangerung',es:'Extension del plazo',it:'Estensione scadenza',zh:'项目延长期限'},
'Dear Team,':{fr:'Chere equipe,',de:'Liebes Team,',es:'Estimado equipo,',it:'Caro team,',zh:'各位团队成员，'},
'Best regards':{fr:'Cordialement',de:'Mit freundlichen Grussen',es:'Saludos cordiales',it:'Cordiali saluti',zh:'祝好'},
'From voice to perfect text':{fr:'De la voix au texte parfait',de:'Von Sprache zu perfektem Text',es:'De voz a texto perfecto',it:'Dalla voce al testo perfetto',zh:'从语音到完美文字'},
'Subject:':{fr:'Objet :',de:'Betreff:',es:'Asunto:',it:'Oggetto:',zh:'主题：'},
'Ready to upgrade your workflow?':{fr:'Pret a ameliorer votre flux?',de:'Bereit fur das Upgrade?',es:'Listo para mejorar tu flujo?',it:'Pronto a migliorare il flusso?',zh:'准备好升级工作流了吗？'},
'Speak your language, write in any language':{fr:'Parlez votre langue, ecrivez dans toute langue',de:'Sprechen Sie Ihre Sprache, schreiben in jeder',es:'Habla tu idioma, escribe en cualquiera',it:'Parla la tua lingua, scrivi in qualsiasi',zh:'用你的语言说，用任何语言写'},
'For minds that move faster than fingers':{fr:'Pour les esprits plus rapides que les doigts',de:'Fur Kopfe schneller als Finger',es:'Mentes mas rapidas que los dedos',it:'Menti piu veloci delle dita',zh:'为思考比打字更快的人'},
'Action Item:':{fr:'Action : ',de:'Aufgabe: ',es:'Accion: ',it:'Azione: ',zh:'行动项：'},
'Next Steps:':{fr:'Prochaines etapes : ',de:'Nachste Schritte: ',es:'Proximos pasos: ',it:'Prossimi passi: ',zh:'下一步：'},
// FAQ
'FAQ':{fr:'FAQ',de:'FAQ',es:'FAQ',it:'FAQ',zh:'常见问题'},
'How does the free trial work?':{fr:'Comment fonctionne l\'essai?',de:'Wie funktioniert die Testversion?',es:'Como funciona la prueba?',it:'Come funziona la prova?',zh:'免费试用如何运作？'},
'How long can each recording be?':{fr:'Duree max?',de:'Max. Aufnahmedauer?',es:'Duracion max?',it:'Durata max?',zh:'每条录音可以多长？'},
'What languages does VoiceNote support?':{fr:'Quelles langues?',de:'Welche Sprachen?',es:'Que idiomas?',it:'Quali lingue?',zh:'支持哪些语言？'},
'VoiceNote supports 46 languages for both transcription and AI polishing, covering major languages across Europe, Asia, the Middle East, and the Americas.':{fr:'VoiceNote prend en charge 46 langues pour la transcription et le polissage IA, couvrant l\'Europe, l\'Asie, le Moyen-Orient et les Ameriques.',de:'VoiceNote unterstutzt 46 Sprachen fur Transkription und KI, in Europa, Asien, Nahost und Amerika.',es:'VoiceNote admite 46 idiomas para transcripcion y pulido IA, cubriendo Europa, Asia, Oriente Medio y America.',it:'VoiceNote supporta 46 lingue per trascrizione e perfezionamento IA, coprendo Europa, Asia, Medio Oriente e Americhe.',zh:'VoiceNote 支持 46 种语言转录和 AI 润色，覆盖欧洲、亚洲、中东和美洲。'},
'Do you offer a refund guarantee?':{fr:'Offrez-vous une garantie?',de:'Ruckerstattung?',es:'Garantia de reembolso?',it:'Garanzia di rimborso?',zh:'有退款保证吗？'},
'Yes. We back all paid plans with a 7-day money-back guarantee. If you\'re not satisfied within the first week, contact support and we\'ll issue a full refund.':{fr:'Oui. Garantie de 7 jours. Pas satisfait? Contactez le support pour un remboursement.',de:'Ja. 7-Tage-Geld-zuruck. Nicht zufrieden? Support fur Ruckerstattung.',es:'Si. Garantia de 7 dias. Si no estas satisfecho, contacta soporte para reembolso.',it:'Si. Garanzia di 7 giorni. Non soddisfatto? Contatta supporto per rimborso.',zh:'是的。7 天退款保证。不满意联系支持全额退款。'},
'Do you offer a refund guarantee?':{fr:'Offrez-vous une garantie?',de:'Ruckerstattung?',es:'Garantia de reembolso?',it:'Garanzia di rimborso?',zh:'有退款保证吗？'},
// Download page
'iOS App':{fr:'App iOS',de:'iOS App',es:'App iOS',it:'App iOS',zh:'iOS 应用'},
'Scan to get VoiceNote':{fr:'Scanner pour VoiceNote',de:'Scannen fur VoiceNote',es:'Escanear para VoiceNote',it:'Scansiona per VoiceNote',zh:'扫码获取 VoiceNote'},
'Free vs ':{fr:'Gratuit vs ',de:'Kostenlos vs ',es:'Gratis vs ',it:'Gratis vs ',zh:'免费 vs '},
'Scan to':{fr:'Scanner pour',de:'Scannen fur',es:'Escanear para',it:'Scansiona per',zh:'扫码'},
'Scan to ': {fr:'Scanner pour ',de:'Scannen fur ',es:'Escanear para ',it:'Scansiona per ',zh:'扫码'},
'get VoiceNote':{fr:'obtenir VoiceNote',de:'VoiceNote erhalten',es:'obtener VoiceNote',it:'ottenere VoiceNote',zh:'获取 VoiceNote'},
'We\'d love to ': {fr:'Nous aimerions ',de:'Wir wurden gerne ',es:'Nos encantaria ',it:'Ci piacerebbe ',zh:'我们期待 '},
'hear from you':{fr:'vous entendre',de:'von Ihnen horen',es:'saber de ti',it:'sentirti',zh:'收到你的消息'},
'Got a question, found a bug, or want to suggest a new AI style? Drop us a line and our team will get back to you within 24 hours.':{fr:'Une question, un bug, ou une suggestion de style IA? Ecrivez-nous, notre equipe vous repondra sous 24h.',de:'Eine Frage, ein Bug oder ein Vorschlag? Schreiben Sie uns, wir antworten innerhalb von 24h.',es:'Una pregunta, un error o una sugerencia? Escribenos, te respondemos en 24h.',it:'Una domanda, un bug o un suggerimento? Scrivici, rispondiamo entro 24h.',zh:'有问题、Bug 或想建议新的 AI 风格？联系我们，24 小时内回复。'},
'Try it ': {fr:'Essayez ',de:'Testen Sie ',es:'Pruebalo ',it:'Provalo ',zh:'免费'},
'Try it': {fr:'Essayez',de:'Testen',es:'Pruebalo',it:'Provalo',zh:'试用'},
'free.':{fr:'gratuitement.',de:'kostenlos.',es:'gratis.',it:'gratis.',zh:'试用。'},
'Free vs ': {fr:'Gratuit vs ',de:'Kostenlos vs ',es:'Gratis vs ',it:'Gratuito vs ',zh:'免费版 vs '},
'Everything in Free, plus unlimited':{fr:'Tout Free en illimite',de:'Alles von Free unbegrenzt',es:'Todo Free ilimitado',it:'Tutto Free illimitato',zh:'免费版全部 + 无限使用'},
'choose a Prime plan to continue using VoiceNote':{fr:'choisissez Premium pour continuer',de:'wahlen Sie Prime',es:'elige Premium para continuar',it:'scegli Premium per continuare',zh:'选择高级版继续使用'},
'choose a Prime plan to keep recording':{fr:'choisissez Premium',de:'Prime wahlen',es:'elige Premium',it:'scegli Premium',zh:'选择高级版继续'},
'Up to 15 minutes per recording on Prime.':{fr:'Jusqu\'a 15 min sur Premium.',de:'Bis zu 15 Min auf Prime.',es:'Hasta 15 min en Premium.',it:'Fino a 15 min su Premium.',zh:'高级版最长 15 分钟。'},
'Up to 15 minutes per recording on Prime. That\'s more than enough for meeting recaps, journal entries, brain dumps, and detailed briefs.':{fr:'Jusqu\'a 15 min sur Premium. Ideal pour reunions, journal, brainstorming.',de:'Bis zu 15 Min auf Prime. Genug fur Meetings, Tagebuch, Brainstorming.',es:'Hasta 15 min en Premium. Suficiente para reuniones, diario, ideas.',it:'Fino a 15 min su Premium. Abbastanza per riunioni, diario, brainstorming.',zh:'高级版最长 15 分钟。足以应对会议记录、日记、头脑风暴和简报。'},
'Your first 10 notes are completely free (up to 2 minutes each). No credit card required. After that, choose a Prime plan to keep recording.':{fr:'Vos 10 premieres notes sont gratuites (2 min max). Sans CB. Ensuite, choisissez Premium.',de:'Ihre ersten 10 Notizen sind kostenlos (2 Min). Keine Karte. Danach Prime wahlen.',es:'Tus 10 primeras notas son gratis (2 min). Sin tarjeta. Luego, elige Premium.',it:'Le tue prime 10 note sono gratis (2 min). Nessuna carta. Poi scegli Premium.',zh:'前 10 条笔记免费（每条 2 分钟）。无需信用卡。之后选择高级版继续使用。'},
'Free vs Prime':{fr:'Gratuit vs Premium',de:'Kostenlos vs Prime',es:'Gratis vs Premium',it:'Gratuito vs Premium',zh:'免费版 vs 高级版'},
'free.':{fr:'gratuitement.',de:'kostenlos.',es:'gratis.',it:'gratis.',zh:'免费。'},
'endless possibilities':{fr:'possibilites infinies',de:'endlose Moglichkeiten',es:'infinitas posibilidades',it:'infinite possibilita',zh:'无限可能'},
'Start Here':{fr:'Commencez ici',de:'Hier starten',es:'Empieza aqui',it:'Inizia qui',zh:'从这里开始'},
// Language chips
'Francais':{fr:'Francais',de:'Francais',es:'Francais',it:'Francais',zh:'Francais'},
'Nederlands':{fr:'Nederlands',de:'Nederlands',es:'Nederlands',it:'Nederlands',zh:'Nederlands'},
'Portugues':{fr:'Portugues',de:'Portugues',es:'Portugues',it:'Portugues',zh:'Portugues'},
'Svenska':{fr:'Svenska',de:'Svenska',es:'Svenska',it:'Svenska',zh:'Svenska'},
'Polski':{fr:'Polski',de:'Polski',es:'Polski',it:'Polski',zh:'Polski'},
'Turkce':{fr:'Turkce',de:'Turkce',es:'Turkce',it:'Turkce',zh:'Turkce'},
'Русский':{fr:'Russe',de:'Russisch',es:'Ruso',it:'Russo',zh:'俄语'},
'العربية':{fr:'Arabe',de:'Arabisch',es:'Arabe',it:'Arabo',zh:'阿拉伯语'},
'日本語':{fr:'Japonais',de:'Japanisch',es:'Japones',it:'Giapponese',zh:'日语'},
'한국어':{fr:'Coreen',de:'Koreanisch',es:'Coreano',it:'Coreano',zh:'韩语'},
'中文':{fr:'Chinois',de:'Chinesisch',es:'Chino',it:'Cinese',zh:'中文'},
// Remaining fragments
'We\'d love to':{fr:'Nous aimerions',de:'Wir wurden gerne',es:'Nos encantaria',it:'Ci piacerebbe',zh:'我们期待'},
'Drop us a line anytime. We\'ll get back to you within 24 hours.':{fr:'Ecrivez-nous. Reponse sous 24h.',de:'Schreiben Sie uns. Antwort in 24h.',es:'Escribenos. Respondemos en 24h.',it:'Scrivici. Rispondiamo entro 24h.',zh:'联系我们，24 小时内回复。'},
// Pricing FAQ answers
'Absolutely. You can upgrade, downgrade, or cancel directly from the app. Changes take effect at the end of your current billing period.':{fr:'Absolument. Mettez a niveau ou annulez depuis l\'app. Les changements prennent effet a la fin de la periode.',de:'Ja. Andern Sie direkt in der App. Anderungen werden zum Ende des Abrechnungszeitraums wirksam.',es:'Por supuesto. Cambia o cancela desde la app. Los cambios se aplican al final del periodo.',it:'Certamente. Aggiorna o annulla dall\'app. Le modifiche hanno effetto alla fine del periodo.',zh:'当然。可以直接从 App 升级或取消。变更在当前周期结束时生效。'},
'Your first 10 notes are completely free (up to 2 minutes each). No credit card required. After that, choose a Prime plan to keep recording.':{fr:'Vos 10 premieres notes sont gratuites (2 min max). Sans CB. Ensuite, choisissez Prime.',de:'Ihre ersten 10 Notizen sind kostenlos. Keine Kreditkarte. Danach Prime wahlen.',es:'Tus 10 primeras notas son gratis. Sin tarjeta. Luego, elige Prime.',it:'Le tue prime 10 note sono gratis. Nessuna carta. Poi scegli Prime.',zh:'前 10 条笔记完全免费（每条 2 分钟）。无需信用卡。之后选 Prime。'},
'Your notes are yours. If you cancel, you\'ll still have read-only access to all your existing notes. You can export them anytime.':{fr:'Vos notes sont a vous. Si vous annulez, acces en lecture seule conserve. Exportez a tout moment.',de:'Ihre Notizen gehoren Ihnen. Nach Kundigung Lesezugriff. Export jederzeit moglich.',es:'Tus notas son tuyas. Si cancelas, acceso de solo lectura. Exporta cuando quieras.',it:'Le tue note sono tue. Se annulli, accesso in sola lettura. Esporta quando vuoi.',zh:'笔记属于你。取消后仍可只读访问，随时导出。'},
'Up to 15 minutes per recording on Prime. That\'s more than enough for meeting recaps, journal entries, brain dumps, and detailed briefs.':{fr:'Jusqu\'a 15 min sur Prime. Ideal pour reunions, journal, brainstorming.',de:'Bis zu 15 Min auf Prime. Genug fur Meetings, Tagebuch, Brainstorming.',es:'Hasta 15 min en Prime. Suficiente para reuniones, diario, ideas.',it:'Fino a 15 min su Prime. Abbastanza per riunioni, diario, brainstorming.',zh:'Prime 最长 15 分钟。足以应对会议、日记和头脑风暴。'},
'Inside the App':{fr:'Dans l\'App',de:'In der App',es:'Dentro de la App',it:'Dentro l\'App',zh:'应用预览'},
'Record in one tap':{fr:'Enregistrer en un clic',de:'Ein-Tipp-Aufnahme',es:'Grabar en un toque',it:'Registra in un tocco',zh:'一键录音'},
'AI-polished text':{fr:'Texte peaufine IA',de:'KI-verfeinerter Text',es:'Texto pulido IA',it:'Testo perfezionato IA',zh:'AI 润色文字'},
'Organise with tags':{fr:'Organisez avec tags',de:'Mit Tags organisieren',es:'Organiza con etiquetas',it:'Organizza con tag',zh:'标签整理'},
'Get Started':{fr:'Commencer',de:'Loslegen',es:'Empezar',it:'Inizia',zh:'开始'},
'Download the app':{fr:'Telecharger l\'app',de:'App herunterladen',es:'Descargar la app',it:'Scarica l\'app',zh:'下载 App'},
'Create your account':{fr:'Creer votre compte',de:'Konto erstellen',es:'Crea tu cuenta',it:'Crea account',zh:'创建账户'},
'Tap record & speak':{fr:'Enregistrer et parler',de:'Aufnehmen & sprechen',es:'Grabar y hablar',it:'Registra e parla',zh:'点击录音说话'},
'Read, copy, share':{fr:'Lire, copier, partager',de:'Lesen, Kopieren, Teilen',es:'Leer, copiar, compartir',it:'Leggi, copia, condividi',zh:'阅读、复制、分享'},
'Requirements':{fr:'Prerequis',de:'Anforderungen',es:'Requisitos',it:'Requisiti',zh:'系统要求'},
// Contact
'Get the App':{fr:'Obtenir l\'App',de:'App holen',es:'Obtener la App',it:'Ottieni l\'App',zh:'获取应用'},
// Footer
'Privacy Policy':{fr:'Confidentialite',de:'Datenschutz',es:'Privacidad',it:'Privacy',zh:'隐私政策'},
'Terms of Service':{fr:'Conditions',de:'Nutzungsbedingungen',es:'Terminos',it:'Termini',zh:'服务条款'},
'Cookie Policy':{fr:'Cookies',de:'Cookies',es:'Cookies',it:'Cookie',zh:'Cookie 政策'},
// Requirements
'iPhone &amp; iPad &middot; iOS 16.0+':{fr:'iPhone et iPad · iOS 16+',de:'iPhone & iPad · iOS 16+',es:'iPhone y iPad · iOS 16+',it:'iPhone e iPad · iOS 16+',zh:'iPhone 和 iPad · iOS 16+'},
'iPhone or iPad running iOS 16.0 or later':{fr:'iPhone/iPad iOS 16+',de:'iPhone/iPad iOS 16+',es:'iPhone/iPad iOS 16+',it:'iPhone/iPad iOS 16+',zh:'iPhone/iPad iOS 16+'},
// Language names
'English':{fr:'English',de:'English',es:'English',it:'English',zh:'English'},
'Francais':{fr:'Francais',de:'Francais',es:'Francais',it:'Francais',zh:'Francais'},
'Deutsch':{fr:'Deutsch',de:'Deutsch',es:'Deutsch',it:'Deutsch',zh:'Deutsch'},
'Espanol':{fr:'Espanol',de:'Espanol',es:'Espanol',it:'Espanol',zh:'Espanol'},
'Italiano':{fr:'Italiano',de:'Italiano',es:'Italiano',it:'Italiano',zh:'Italiano'},
// Short labels
'iOS':{fr:'iOS',de:'iOS',es:'iOS',it:'iOS',zh:'iOS'},
'Coming soon':{fr:'Bientot',de:'Demnachst',es:'Proximamente',it:'Prossimamente',zh:'即将上线'},
'$9.99':{fr:'9,99$',de:'9,99$',es:'$9.99',it:'9,99$',zh:'$9.99'},
'$25':{fr:'25$',de:'25$',es:'$25',it:'25$',zh:'$25'},
'$69':{fr:'69$',de:'69$',es:'$69',it:'69$',zh:'$69'},
'/mo':{fr:'/mois',de:'/Monat',es:'/mes',it:'/mese',zh:'/月'},
'/qtr':{fr:'/trim',de:'/Quartal',es:'/trim',it:'/trim',zh:'/季'},
'/yr':{fr:'/an',de:'/Jahr',es:'/ano',it:'/anno',zh:'/年'},
'Save 28% with annual billing':{fr:'Economisez 28%/an',de:'28% sparen/Jahr',es:'Ahorra 28%/ano',it:'Risparmia 28%/anno',zh:'年付省 28%'},
'Cancel anytime':{fr:'Annulez a tout moment',de:'Jederzeit kundbar',es:'Cancela cuando quieras',it:'Annulla quando vuoi',zh:'随时取消'},
// Legal pages
'Legal':{fr:'Juridique',de:'Rechtliches',es:'Legal',it:'Legale',zh:'法律'},
'Last updated: May 2026':{fr:'Derniere mise a jour: Mai 2026',de:'Zuletzt aktualisiert: Mai 2026',es:'Actualizado: Mayo 2026',it:'Ultimo aggiornamento: Maggio 2026',zh:'最近更新：2026年5月'},
'At VoiceNote, we protect your voice. We believe your thoughts and recordings are strictly personal. This Privacy Policy explains how we collect, use, and safeguard your information.':{fr:'Chez VoiceNote, nous protegeons votre voix. Nous croyons que vos pensees et enregistrements sont strictement personnels. Cette politique explique comment nous collectons, utilisons et protegeons vos informations.',de:'Bei VoiceNote schutzen wir Ihre Stimme. Ihre Gedanken und Aufnahmen sind personlich. Diese Richtlinie erklart, wie wir Ihre Daten erfassen, nutzen und schutzen.',es:'En VoiceNote, protegemos tu voz. Creemos que tus pensamientos y grabaciones son estrictamente personales. Esta politica explica como recopilamos, usamos y protegemos tu informacion.',it:'In VoiceNote, proteggiamo la tua voce. Crediamo che i tuoi pensieri e le registrazioni siano strettamente personali. Questa informativa spiega come raccogliamo, utilizziamo e proteggiamo i tuoi dati.',zh:'在 VoiceNote，我们保护你的声音。我们相信你的想法和录音是严格保密的。本隐私政策说明我们如何收集、使用和保护你的信息。'},
'1. Information We Collect':{fr:'1. Informations que nous collectons',de:'1. Von uns erfasste Daten',es:'1. Informacion que recopilamos',it:'1. Informazioni che raccogliamo',zh:'1. 我们收集的信息'},
'We collect information that you provide directly to us:':{fr:'Nous collectons les informations que vous nous fournissez :',de:'Wir erfassen Daten, die Sie uns direkt bereitstellen:',es:'Recopilamos la informacion que nos proporcionas:',it:'Raccogliamo le informazioni che ci fornisci:',zh:'我们收集你直接提供给我们的信息：'},
'Account Information:':{fr:'Informations du compte :',de:'Kontoinformationen:',es:'Informacion de cuenta:',it:'Informazioni account:',zh:'账户信息：'},
'Name, email address, and password when you create an account.':{fr:'Nom, adresse e-mail et mot de passe lors de la creation du compte.',de:'Name, E-Mail und Passwort bei Kontoerstellung.',es:'Nombre, email y contrasena al crear cuenta.',it:'Nome, email e password al momento della creazione dell\'account.',zh:'创建账户时的姓名、邮箱和密码。'},
'Voice Recordings:':{fr:'Enregistrements vocaux :',de:'Sprachaufnahmen:',es:'Grabaciones de voz:',it:'Registrazioni vocali:',zh:'语音录音：'},
'Audio files you record or upload for transcription and processing.':{fr:'Fichiers audio que vous enregistrez ou televersez pour transcription.',de:'Audiodateien, die Sie zur Transkription aufnehmen oder hochladen.',es:'Archivos de audio que grabas o subes para transcripcion.',it:'File audio che registri o carichi per la trascrizione.',zh:'你录制或上传用于转录和处理的音频文件。'},
'Usage Data:':{fr:'Donnees d\'utilisation :',de:'Nutzungsdaten:',es:'Datos de uso:',it:'Dati di utilizzo:',zh:'使用数据：'},
'Information about how you use VoiceNote, including feature usage and interaction patterns.':{fr:'Informations sur votre utilisation de VoiceNote.',de:'Informationen zur Nutzung von VoiceNote.',es:'Informacion sobre como usas VoiceNote.',it:'Informazioni sull\'uso di VoiceNote.',zh:'关于你如何使用 VoiceNote 的信息。'},
'Device Information:':{fr:'Informations sur l\'appareil :',de:'Geratteinformationen:',es:'Informacion del dispositivo:',it:'Informazioni dispositivo:',zh:'设备信息：'},
'Device type, operating system, and app version.':{fr:'Type d\'appareil, systeme d\'exploitation et version de l\'application.',de:'Geratetyp, Betriebssystem und App-Version.',es:'Tipo de dispositivo, sistema operativo y version de la app.',it:'Tipo di dispositivo, sistema operativo e versione dell\'app.',zh:'设备类型、操作系统和应用版本。'},
'2. How We Use Your Information':{fr:'2. Comment nous utilisons vos informations',de:'2. Wie wir Ihre Daten verwenden',es:'2. Como usamos tu informacion',it:'2. Come utilizziamo i tuoi dati',zh:'2. 我们如何使用你的信息'},
'To provide, maintain, and improve our services':{fr:'Fournir, maintenir et ameliorer nos services',de:'Bereitstellung und Verbesserung unserer Dienste',es:'Proporcionar y mejorar nuestros servicios',it:'Fornire e migliorare i nostri servizi',zh:'提供、维护和改进我们的服务'},
'To process your voice recordings into text using AI':{fr:'Traiter vos enregistrements vocaux en texte via l\'IA',de:'Ihre Aufnahmen mit KI in Text umwandeln',es:'Procesar tus grabaciones en texto con IA',it:'Elaborare le tue registrazioni in testo con IA',zh:'用 AI 将你的语音转换为文字'},
'To send you important updates and notifications':{fr:'Vous envoyer des mises a jour importantes',de:'Wichtige Updates und Benachrichtigungen senden',es:'Enviarte actualizaciones importantes',it:'Inviarti aggiornamenti importanti',zh:'向你发送重要更新和通知'},
'To respond to your comments, questions, and support requests':{fr:'Repondre a vos commentaires et demandes d\'assistance',de:'Auf Ihre Kommentare und Supportanfragen antworten',es:'Responder a tus comentarios y solicitudes',it:'Rispondere ai tuoi commenti e richieste',zh:'回复你的评论、问题和支持请求'},
'To analyze usage patterns and improve user experience':{fr:'Analyser l\'utilisation et ameliorer l\'experience',de:'Nutzungsmuster analysieren und Erfahrung verbessern',es:'Analizar patrones de uso y mejorar la experiencia',it:'Analizzare l\'uso e migliorare l\'esperienza',zh:'分析使用模式并改善用户体验'},
'3. AI Processing & Data Storage':{fr:'3. Traitement IA et stockage des donnees',de:'3. KI-Verarbeitung & Datenspeicherung',es:'3. Procesamiento IA y almacenamiento',it:'3. Elaborazione IA e archiviazione dati',zh:'3. AI 处理与数据存储'},
'Your audio files are processed securely using temporary API calls and are deleted immediately after transcription. We do not use your voice to train public AI models. Transcribed text is stored securely in your account.':{fr:'Vos fichiers audio sont traites securitairement via des appels API temporaires et supprimes apres transcription. Nous n\'utilisons pas votre voix pour entrainer des modeles IA publics.',de:'Ihre Audiodateien werden sicher verarbeitet und nach der Transkription geloscht. Wir nutzen Ihre Stimme nicht zum Trainieren offentlicher KI-Modelle.',es:'Tus archivos de audio se procesan de forma segura y se eliminan despues de la transcripcion. No usamos tu voz para entrenar modelos de IA publicos.',it:'I tuoi file audio vengono elaborati in modo sicuro ed eliminati dopo la trascrizione. Non usiamo la tua voce per addestrare modelli IA pubblici.',zh:'你的音频文件通过临时 API 安全处理，转录后立即删除。我们不会用你的声音训练公开 AI 模型。转录文本安全存储在你的账户中。'},
'4. Data Sharing':{fr:'4. Partage des donnees',de:'4. Datenweitergabe',es:'4. Comparticion de datos',it:'4. Condivisione dei dati',zh:'4. 数据共享'},
'We do not sell, trade, or rent your personal information to third parties. We may share data with:':{fr:'Nous ne vendons, n\'echangeons ni ne louons vos donnees personnelles. Nous pouvons les partager avec :',de:'Wir verkaufen Ihre Daten nicht. Wir konnen sie weitergeben an:',es:'No vendemos ni alquilamos tu informacion. Podemos compartir datos con:',it:'Non vendiamo ne affittiamo i tuoi dati. Possiamo condividerli con:',zh:'我们不出售、交易或出租你的个人信息。我们可能与以下方共享数据：'},
'AI service providers solely for the purpose of processing your recordings':{fr:'Fournisseurs de services IA uniquement pour le traitement de vos enregistrements',de:'KI-Dienstleister nur zur Verarbeitung Ihrer Aufnahmen',es:'Proveedores de IA solo para procesar tus grabaciones',it:'Fornitori di servizi IA solo per elaborare le tue registrazioni',zh:'AI 服务提供商仅用于处理你的录音'},
'Law enforcement when required by applicable law':{fr:'Forces de l\'ordre lorsque la loi l\'exige',de:'Strafverfolgungsbehorden wenn gesetzlich vorgeschrieben',es:'Autoridades cuando lo exija la ley',it:'Forze dell\'ordine quando richiesto dalla legge',zh:'法律要求时的执法机构'},
'5. Data Security':{fr:'5. Securite des donnees',de:'5. Datensicherheit',es:'5. Seguridad de datos',it:'5. Sicurezza dei dati',zh:'5. 数据安全'},
'6. Your Rights':{fr:'6. Vos droits',de:'6. Ihre Rechte',es:'6. Tus derechos',it:'6. I tuoi diritti',zh:'6. 你的权利'},
'7. Contact':{fr:'7. Contact',de:'7. Kontakt',es:'7. Contacto',it:'7. Contatto',zh:'7. 联系方式'},
// Terms
'Welcome to VoiceNote. By accessing or using our application and website, you agree to be bound by these Terms of Service. Please read them carefully.':{fr:'Bienvenue sur VoiceNote. En accedant a notre application et site web, vous acceptez ces conditions. Veuillez les lire attentivement.',de:'Willkommen bei VoiceNote. Durch den Zugriff auf unsere App und Website stimmen Sie diesen Bedingungen zu. Bitte lesen Sie sie sorgfaltig.',es:'Bienvenido a VoiceNote. Al acceder a nuestra aplicacion y sitio web, aceptas estos terminos. Leelos atentamente.',it:'Benvenuto su VoiceNote. Accedendo alla nostra app e sito web, accetti questi termini. Leggili attentamente.',zh:'欢迎使用 VoiceNote。访问或使用我们的应用和网站，即表示你同意遵守这些服务条款。请仔细阅读。'},
'This Cookie Policy explains what cookies are, how VoiceNote uses them, and your choices regarding cookies.':{fr:'Cette politique explique ce que sont les cookies, comment VoiceNote les utilise et vos choix.',de:'Diese Cookie-Richtlinie erklart, was Cookies sind, wie VoiceNote sie verwendet und Ihre Wahlmoglichkeiten.',es:'Esta politica explica que son las cookies, como las usa VoiceNote y tus opciones.',it:'Questa politica spiega cosa sono i cookie, come VoiceNote li utilizza e le tue scelte.',zh:'本 Cookie 政策解释什么是 Cookie、VoiceNote 如何使用它们以及你的选择。'},
'1. Acceptance of Terms':{fr:'1. Acceptation des conditions',de:'1. Annahme der Bedingungen',es:'1. Aceptacion de terminos',it:'1. Accettazione dei termini',zh:'1. 接受条款'},
'2. Account Registration':{fr:'2. Creation de compte',de:'2. Kontoregistrierung',es:'2. Registro de cuenta',it:'2. Registrazione account',zh:'2. 账户注册'},
'3. Use of Services':{fr:'3. Utilisation des services',de:'3. Nutzung der Dienste',es:'3. Uso de servicios',it:'3. Utilizzo dei servizi',zh:'3. 服务使用'},
'4. Subscriptions & Payments':{fr:'4. Abonnements et paiements',de:'4. Abos & Zahlungen',es:'4. Suscripciones y pagos',it:'4. Abbonamenti e pagamenti',zh:'4. 订阅与支付'},
'5. Intellectual Property':{fr:'5. Propriete intellectuelle',de:'5. Geistiges Eigentum',es:'5. Propiedad intelectual',it:'5. Proprieta intellettuale',zh:'5. 知识产权'},
'6. Limitation of Liability':{fr:'6. Limitation de responsabilite',de:'6. Haftungsbeschrankung',es:'6. Limitacion de responsabilidad',it:'6. Limitazione di responsabilita',zh:'6. 责任限制'},
'8. Changes to Terms':{fr:'8. Modifications des conditions',de:'8. Anderungen der Bedingungen',es:'8. Cambios en los terminos',it:'8. Modifiche ai termini',zh:'8. 条款变更'},
// Cookies
'What Are Cookies':{fr:'Que sont les cookies',de:'Was sind Cookies',es:'Que son las cookies',it:'Cosa sono i cookie',zh:'什么是 Cookie'},
'Cookies are small text files stored on your device when you visit a website. They help websites remember your preferences, logins, and other settings to improve your browsing experience.':{fr:'Les cookies sont de petits fichiers texte stockes sur votre appareil. Ils aident les sites a memoriser vos preferences.',de:'Cookies sind kleine Textdateien, die auf Ihrem Gerat gespeichert werden. Sie helfen Websites, sich an Ihre Einstellungen zu erinnern.',es:'Las cookies son pequenos archivos de texto almacenados en tu dispositivo. Ayudan a recordar preferencias.',it:'I cookie sono piccoli file di testo memorizzati sul tuo dispositivo. Aiutano i siti a ricordare le tue preferenze.',zh:'Cookie 是存储在你设备上的小型文本文件。它们帮助网站记住你的偏好和设置。'},
'How We Use Cookies':{fr:'Comment nous utilisons les cookies',de:'Wie wir Cookies verwenden',es:'Como usamos las cookies',it:'Come usiamo i cookie',zh:'我们如何使用 Cookie'},
'VoiceNote uses cookies for the following purposes:':{fr:'VoiceNote utilise des cookies pour :',de:'VoiceNote verwendet Cookies fur:',es:'VoiceNote usa cookies para:',it:'VoiceNote utilizza i cookie per:',zh:'VoiceNote 将 Cookie 用于以下目的：'},
'Category':{fr:'Categorie',de:'Kategorie',es:'Categoria',it:'Categoria',zh:'类别'},
'Purpose':{fr:'Objectif',de:'Zweck',es:'Proposito',it:'Scopo',zh:'用途'},
'Duration':{fr:'Duree',de:'Dauer',es:'Duracion',it:'Durata',zh:'有效期'},
'Essential':{fr:'Essentiel',de:'Notwendig',es:'Esencial',it:'Essenziale',zh:'必要'},
'Required for the website to function':{fr:'Necessaire au fonctionnement du site',de:'Erforderlich fur die Website',es:'Necesario para el funcionamiento',it:'Necessario per il funzionamento',zh:'网站运行所必需'},
'Preferences':{fr:'Preferences',de:'Einstellungen',es:'Preferencias',it:'Preferenze',zh:'偏好'},
'Remember your settings such as language and theme preferences':{fr:'Memoriser vos preferences de langue et de theme',de:'Sprach- und Designeinstellungen speichern',es:'Recordar idioma y preferencias',it:'Ricordare lingua e preferenze',zh:'记住你的语言和主题偏好'},
'Analytics':{fr:'Analyse',de:'Analyse',es:'Analitica',it:'Analitica',zh:'分析'},
'Help us understand how visitors use our site so we can improve it':{fr:'Nous aident a comprendre l\'utilisation du site',de:'Helfen uns zu verstehen, wie Besucher die Seite nutzen',es:'Nos ayudan a entender como se usa el sitio',it:'Ci aiutano a capire come viene usato il sito',zh:'帮助我们了解访问者如何使用网站'},
'Functional':{fr:'Fonctionnel',de:'Funktional',es:'Funcional',it:'Funzionale',zh:'功能'},
'Enable additional features like audio recording and playback':{fr:'Permettent des fonctionnalites comme l\'enregistrement audio',de:'Ermoglichen zusatzliche Funktionen wie Audioaufnahme',es:'Permiten funciones adicionales como grabacion de audio',it:'Abilitano funzioni aggiuntive come la registrazione audio',zh:'启用录音和播放等附加功能'},
'Third-Party Cookies':{fr:'Cookies tiers',de:'Cookies von Drittanbietern',es:'Cookies de terceros',it:'Cookie di terze parti',zh:'第三方 Cookie'},
'Some cookies are placed by third-party services we use:':{fr:'Certains cookies sont places par des services tiers :',de:'Einige Cookies werden von Drittanbietern gesetzt:',es:'Algunas cookies son colocadas por servicios de terceros:',it:'Alcuni cookie sono impostati da servizi di terze parti:',zh:'部分 Cookie 由我们使用的第三方服务设置：'},
'Stripe:':{fr:'Stripe :',de:'Stripe:',es:'Stripe:',it:'Stripe:',zh:'Stripe：'},
'Payment processing (functional cookies)':{fr:'Traitement des paiements (cookies fonctionnels)',de:'Zahlungsabwicklung (funktionale Cookies)',es:'Procesamiento de pagos (cookies funcionales)',it:'Elaborazione pagamenti (cookie funzionali)',zh:'支付处理（功能 Cookie）'},
'Cloudflare:':{fr:'Cloudflare :',de:'Cloudflare:',es:'Cloudflare:',it:'Cloudflare:',zh:'Cloudflare：'},
'Security and performance (essential cookies)':{fr:'Securite et performance (cookies essentiels)',de:'Sicherheit und Leistung (notwendige Cookies)',es:'Seguridad y rendimiento (cookies esenciales)',it:'Sicurezza e prestazioni (cookie essenziali)',zh:'安全与性能（必要 Cookie）'},
'Your Choices':{fr:'Vos choix',de:'Ihre Wahlmoglichkeiten',es:'Tus opciones',it:'Le tue scelte',zh:'你的选择'},
'You can control cookies through your browser settings. Most browsers allow you to:':{fr:'Vous pouvez controler les cookies via les parametres de votre navigateur :',de:'Sie konnen Cookies uber Ihre Browsereinstellungen steuern:',es:'Puedes controlar las cookies desde la configuracion del navegador:',it:'Puoi controllare i cookie dalle impostazioni del browser:',zh:'你可以通过浏览器设置管理 Cookie：'},
'View and delete existing cookies':{fr:'Voir et supprimer les cookies existants',de:'Vorhandene Cookies anzeigen und loschen',es:'Ver y eliminar cookies existentes',it:'Visualizzare ed eliminare i cookie esistenti',zh:'查看和删除已有 Cookie'},
'Block third-party cookies':{fr:'Bloquer les cookies tiers',de:'Cookies von Drittanbietern blockieren',es:'Bloquear cookies de terceros',it:'Bloccare i cookie di terze parti',zh:'阻止第三方 Cookie'},
'Block all cookies':{fr:'Bloquer tous les cookies',de:'Alle Cookies blockieren',es:'Bloquear todas las cookies',it:'Bloccare tutti i cookie',zh:'阻止所有 Cookie'},
'Clear cookies when you close the browser':{fr:'Supprimer les cookies a la fermeture du navigateur',de:'Cookies beim Schlieben des Browsers loschen',es:'Eliminar cookies al cerrar el navegador',it:'Cancellare i cookie alla chiusura del browser',zh:'关闭浏览器时清除 Cookie'},
'Cookie Consent':{fr:'Consentement aux cookies',de:'Cookie-Zustimmung',es:'Consentimiento de cookies',it:'Consenso cookie',zh:'Cookie 同意'},
'Changes to This Policy':{fr:'Modifications de cette politique',de:'Anderungen dieser Richtlinie',es:'Cambios en esta politica',it:'Modifiche a questa politica',zh:'政策变更'},
// Pricing FAQ
'Frequently':{fr:'Questions',de:'Haufig',es:'Preguntas',it:'Domande',zh:'常见'},
'asked questions':{fr:'frequentes',de:'gestellte Fragen',es:'frecuentes',it:'frequenti',zh:'问题解答'},
'Can I switch or cancel my plan anytime?':{fr:'Puis-je changer ou annuler mon plan?',de:'Kann ich wechseln oder kundigen?',es:'Puedo cambiar o cancelar?',it:'Posso cambiare o annullare?',zh:'可以随时切换方案吗？'},
'What happens to my notes if I cancel?':{fr:'Que deviennent mes notes si j\'annule?',de:'Was passiert mit meinen Notizen?',es:'Que pasa con mis notas si cancelo?',it:'Cosa succede alle mie note?',zh:'取消后我的笔记会怎样？'},
'Tags & folders':{fr:'Tags et dossiers',de:'Tags & Ordner',es:'Etiquetas y carpetas',it:'Tag e cartelle',zh:'标签和文件夹'},
// Download page
'Capture your ideas':{fr:'Capturez vos idees',de:'Ideen festhalten',es:'Captura tus ideas',it:'Cattura le idee',zh:'捕捉灵感'},
'anywhere, anytime':{fr:'partout, a tout moment',de:'uberall, jederzeit',es:'en cualquier lugar',it:'ovunque, in ogni momento',zh:'随时随地'},
'Available for iPhone and iPad. Download now and start turning your voice into polished text.':{fr:'Pour iPhone et iPad. Telechargez et transformez votre voix.',de:'Fur iPhone und iPad. Jetzt downloaden.',es:'Para iPhone y iPad. Descarga ahora.',it:'Per iPhone e iPad. Scarica ora.',zh:'适用于 iPhone 和 iPad。立即下载。'},
'Deepgram + GPT refine your words in seconds':{fr:'Deepgram + GPT peaufinent en secondes',de:'Deepgram + GPT verfeinern in Sekunden',es:'Deepgram + GPT refinan en segundos',it:'Deepgram + GPT perfezionano in secondi',zh:'Deepgram + GPT 秒速润色'},
'Folders, tags & full-text search':{fr:'Dossiers, tags et recherche',de:'Ordner, Tags & Volltextsuche',es:'Carpetas, etiquetas y busqueda',it:'Cartelle, tag e ricerca',zh:'文件夹、标签和全文搜索'},
'Get VoiceNote from the App Store. It\'s a free download.':{fr:'Depuis l\'App Store. Gratuit.',de:'Aus dem App Store. Kostenlos.',es:'Desde App Store. Gratis.',it:'Dall\'App Store. Gratis.',zh:'从 App Store 免费下载。'},
'Hit the big record button and start talking. VoiceNote handles the rest.':{fr:'Appuyez et parlez. VoiceNote fait le reste.',de:'Aufnehmen und sprechen. VoiceNote erledigt den Rest.',es:'Pulsa y habla. VoiceNote hace el resto.',it:'Premi e parla. VoiceNote fa il resto.',zh:'点击录音开始说话，VoiceNote 处理剩下的。'},
'Install in':{fr:'Installer en',de:'Installieren in',es:'Instalar en',it:'Installa in',zh:'安装只需'},
'seconds':{fr:'secondes',de:'Sekunden',es:'segundos',it:'secondi',zh:'秒'},
'Minimalist design,':{fr:'Design minimaliste,',de:'Minimalistisch,',es:'Diseno minimo,',it:'Design minimalista,',zh:'极简设计，'},
'maximum productivity':{fr:'productivite maximale',de:'maximale Produktivitat',es:'maxima productividad',it:'massima produttivita',zh:'极致效率'},
'Open your iPhone camera and scan the QR code to download instantly.':{fr:'Ouvrez lappareil photo et scannez.',de:'Kamera offnen und scannen.',es:'Abre la camara y escanea.',it:'Apri la fotocamera e scansiona.',zh:'打开相机扫码下载。'},
'Press the big mic button and start talking':{fr:'Appuyez sur le micro et parlez',de:'Grossen Mikro-Button drucken',es:'Pulsa el microfono y habla',it:'Premi il microfono e parla',zh:'按下麦克风按钮开始说话'},
'Sign up with email or Google. Takes less than 30 seconds.':{fr:'Inscrivez-vous en 30 secondes.',de:'In 30 Sekunden registriert.',es:'Registrate en 30 segundos.',it:'Registrati in 30 secondi.',zh:'邮箱注册，30 秒搞定。'},
'What you':{fr:'Ce dont vous',de:'Was Sie',es:'Lo que',it:'Cosa ti',zh:'你'},
'need':{fr:'avez besoin',de:'brauchen',es:'necesitas',it:'serve',zh:'所需要的'},
'Your polished text is ready. Copy it anywhere, share it, or export it.':{fr:'Votre texte est pret. Copiez, partagez, exportez.',de:'Ihr Text ist fertig. Kopieren, teilen, exportieren.',es:'Tu texto esta listo. Copia, comparte, exporta.',it:'Il tuo testo e pronto. Copia, condividi, esporta.',zh:'文字已就绪。复制、分享或导出。'},
// Contact
'We\'d love to':{fr:'Nous aimerions',de:'Wir wurden gerne',es:'Nos encantaria',it:'Ci piacerebbe',zh:'我们期待'},
'hear from you':{fr:'vous entendre',de:'von Ihnen horen',es:'saber de ti',it:'sentirti',zh:'收到你的消息'},
'Drop us a line anytime. We\'ll get back to you within 24 hours.':{fr:'Ecrivez-nous. Reponse sous 24h.',de:'Schreiben Sie uns. Antwort in 24h.',es:'Escribenos. Respondemos en 24h.',it:'Scrivici. Rispondiamo entro 24h.',zh:'联系我们，24 小时内回复。'},
'Welcome to VoiceNote. By accessing or using our application and website, you agree to be bound by these Terms of Service. Please read them carefully.':{fr:'Bienvenue sur VoiceNote. En accedant, vous acceptez ces conditions.',de:'Willkommen bei VoiceNote. Durch Zugriff stimmen Sie den Bedingungen zu.',es:'Bienvenido a VoiceNote. Al acceder, aceptas estos terminos.',it:'Benvenuto su VoiceNote. Accedendo, accetti questi termini.',zh:'欢迎使用 VoiceNote。访问即表示同意服务条款。'},
'This Cookie Policy explains what cookies are, how VoiceNote uses them, and your choices regarding cookies.':{fr:'Cette politique explique les cookies, leur utilisation et vos choix.',de:'Diese Richtlinie erklart Cookies, deren Nutzung und Ihre Wahlmoglichkeiten.',es:'Esta politica explica las cookies, su uso y tus opciones.',it:'Questa politica spiega i cookie, il loro uso e le tue scelte.',zh:'本政策解释 Cookie 及其使用方式与你的选择。'},
'For questions about these Terms, contact us at':{fr:'Pour questions sur ces conditions :',de:'Fragen zu diesen Bedingungen:',es:'Preguntas sobre estos terminos:',it:'Domande su questi termini:',zh:'条款相关问题请联系：'},
'If you have questions about our Cookie Policy, contact us at':{fr:'Questions sur les cookies :',de:'Fragen zu Cookies:',es:'Preguntas sobre cookies:',it:'Domande sui cookie:',zh:'Cookie 政策问题请联系：'},
'Please note that disabling essential cookies may affect the functionality of VoiceNote.':{fr:'La desactivation des cookies essentiels peut affecter le fonctionnement de VoiceNote.',de:'Deaktivieren notwendiger Cookies kann die Funktionalitat beeintrachtigen.',es:'Desactivar cookies esenciales puede afectar la funcionalidad.',it:'Disabilitare i cookie essenziali puo influire sulla funzionalita.',zh:'禁用必要 Cookie 可能影响 VoiceNote 功能。'},
'When you first visit our website, you will see a cookie banner asking for your consent to non-essential cookies. You can change your preferences at any time through your browser settings or by contacting us.':{fr:'Lors de votre premiere visite, une banniere vous demandera votre consentement. Vous pouvez modifier vos preferences a tout moment.',de:'Beim ersten Besuch erscheint ein Cookie-Banner. Anderungen jederzeit uber Browsereinstellungen moglich.',es:'En tu primera visita, veras un banner de cookies. Cambia preferencias cuando quieras.',it:'Alla prima visita vedrai un banner. Modifica le preferenze in qualsiasi momento.',zh:'首次访问时会看到 Cookie 横幅。可随时通过浏览器或联系我们更改偏好。'},
'We may update this Cookie Policy from time to time. Changes will be posted on this page with an updated date.':{fr:'Nous pouvons mettre a jour cette politique. Les modifications seront publiees avec une date actualisee.',de:'Wir konnen diese Richtlinie aktualisieren. Anderungen werden mit Datum veroffentlicht.',es:'Podemos actualizar esta politica. Los cambios se publicaran con fecha actualizada.',it:'Potremmo aggiornare questa politica. Le modifiche saranno pubblicate con data aggiornata.',zh:'我们可能更新此政策，更改将发布在此页面并注明日期。'},
'You have the right to access, correct, or delete your personal data. You can export your notes at any time. To exercise these rights, contact us at support@voicenote.uk.':{fr:'Vous avez le droit d\'acceder, corriger ou supprimer vos donnees. Exportez vos notes a tout moment. Contactez support@voicenote.uk.',de:'Sie haben das Recht auf Zugriff, Korrektur oder Loschung Ihrer Daten. Export jederzeit moglich. Kontakt: support@voicenote.uk.',es:'Tienes derecho a acceder, corregir o eliminar tus datos. Exporta tus notas cuando quieras. Contacto: support@voicenote.uk.',it:'Hai il diritto di accedere, correggere o eliminare i tuoi dati. Esporta le note in qualsiasi momento. Contatta support@voicenote.uk.',zh:'你有权访问、更正或删除个人数据。可随时导出笔记。联系 support@voicenote.uk。'},
'If you have questions about this Privacy Policy, please contact us at support@voicenote.uk.':{fr:'Questions sur cette politique : support@voicenote.uk.',de:'Fragen zu dieser Richtlinie: support@voicenote.uk.',es:'Preguntas sobre esta politica: support@voicenote.uk.',it:'Domande su questa informativa: support@voicenote.uk.',zh:'隐私政策问题：support@voicenote.uk。'},
'You have the right to access, correct, or delete your personal data. You can export your notes at any time. To exercise these rights, contact us at support@voicenote.uk.':{fr:'Droit d\'acces, correction ou suppression. Export a tout moment. Contact : support@voicenote.uk.',de:'Recht auf Zugriff, Korrektur, Loschung. Export jederzeit. Kontakt: support@voicenote.uk.',es:'Derecho a acceder, corregir o eliminar datos. Exporta cuando quieras. Contacto: support@voicenote.uk.',it:'Diritto di accesso, correzione o cancellazione. Esporta quando vuoi. Contatta: support@voicenote.uk.',zh:'有权访问、更正或删除数据。随时导出。联系 support@voicenote.uk。'},
// Terms — remaining paragraphs
'By creating an account or using VoiceNote in any way, you agree to these Terms. If you do not agree, do not use our services.':{fr:'En creant un compte, vous acceptez ces conditions. Sinon, ne pas utiliser.',de:'Durch Nutzung stimmen Sie zu. Andernfalls nicht nutzen.',es:'Al crear cuenta aceptas. Si no, no uses.',it:'Creando un account accetti. Altrimenti non usare.',zh:'创建账户即同意。如不同意请勿使用。'},
'You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.':{fr:'Informations exactes requises. Vous etes responsable de la confidentialite.',de:'Genaue Angaben notig. Verantwortlich fur Zugangsdaten.',es:'Informacion precisa requerida. Responsable de confidencialidad.',it:'Informazioni accurate richieste. Responsabile della riservatezza.',zh:'需提供准确信息。对账户凭证保密负责。'},
'You agree to use VoiceNote only for lawful purposes. You may not:':{fr:'Utilisation uniquement a des fins licites. Interdit de :',de:'Nur rechtmassige Nutzung. Verboten:',es:'Solo para fines licitos. Prohibido:',it:'Solo per scopi leciti. Vietato:',zh:'仅限合法使用。禁止：'},
'Use the service to create, store, or distribute illegal content':{fr:'Creer, stocker ou distribuer du contenu illegal',de:'Illegale Inhalte',es:'Contenido ilegal',it:'Contenuti illegali',zh:'传播非法内容'},
'Violate any applicable laws or regulations':{fr:'Violer les lois applicables',de:'Gesetze verletzen',es:'Violar leyes',it:'Violare leggi',zh:'违反法律法规'},
'Attempt to gain unauthorized access to our systems':{fr:'Acces non autorise a nos systemes',de:'Unbefugter Zugriff',es:'Acceso no autorizado',it:'Accesso non autorizzato',zh:'未经授权访问系统'},
'Resell or redistribute the service without authorization':{fr:'Revendre sans autorisation',de:'Unbefugter Weiterverkauf',es:'Revender sin permiso',it:'Rivendere senza permesso',zh:'未经授权转售'},
'Use the service to harass, abuse, or harm others':{fr:'Harcelement ou nuisance',de:'Belastigung',es:'Acoso o dano',it:'Molestie o danni',zh:'骚扰或伤害他人'},
'VoiceNote offers both free and paid subscription plans. Paid subscriptions are billed in advance on a monthly or annual basis. All payments are non-refundable except as required by law or as explicitly stated in our refund policy. We offer a 7-day free trial for new Pro and Prime subscribers.':{fr:'Abonnements gratuits et payants, factures a l\'avance. Essai gratuit de 7 jours.',de:'Kostenlose und kostenpflichtige Abos. 7-Tage-Testversion.',es:'Planes gratis y de pago. Prueba de 7 dias.',it:'Piani gratis e a pagamento. Prova di 7 giorni.',zh:'免费和付费方案。7 天免费试用。'},
'You retain all rights to the content you create using VoiceNote. We do not claim ownership of your notes or recordings. VoiceNote, its logo, and all related trademarks are our exclusive property.':{fr:'Vous conservez les droits. VoiceNote et son logo sont notre propriete.',de:'Sie behalten Rechte. VoiceNote und Logo sind unser Eigentum.',es:'Conservas derechos. VoiceNote y logo son nuestra propiedad.',it:'Conservi i diritti. VoiceNote e logo sono nostra proprieta.',zh:'保留内容权利。商标归我们所有。'},
'VoiceNote is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including loss of data or profits, to the fullest extent permitted by law.':{fr:'Fourni "tel quel" sans garantie. Non responsables des dommages.',de:'"Wie besehen" ohne Gewahrleistung. Keine Haftung.',es:'"Tal cual" sin garantia. No responsables de danos.',it:'"Cosi com\'e" senza garanzie. Non responsabili per danni.',zh:'"按原样"提供，不承担损害责任。'},
'We may suspend or terminate your account at any time for violation of these Terms. You may delete your account at any time. Upon termination, your right to use the service will immediately cease.':{fr:'Suspension possible pour violation. Suppression de compte possible.',de:'Sperrung bei Verstoben moglich. Loschung jederzeit.',es:'Suspension por violacion. Puedes eliminar cuenta.',it:'Sospensione per violazione. Puoi eliminare l\'account.',zh:'违规可暂停账户。可随时删除账户。'},
'We reserve the right to modify these Terms at any time. We will notify users of material changes via email or in-app notification. Continued use after changes constitutes acceptance.':{fr:'Modification possible. Notification des changements. Usage continu = acceptation.',de:'Anderungen vorbehalten. Benachrichtigung bei wesentlichen Anderungen.',es:'Podemos modificar. Notificaremos cambios. Uso continuo = aceptacion.',it:'Modifiche possibili. Notifica modifiche. Uso continuato = accettazione.',zh:'保留修改权。通知重大变更。继续使用即接受。'},
// Missing fragments
'From voice to perfect text in 3 steps':{fr:'De la voix au texte parfait en 3 etapes',de:'Von Sprache zu perfektem Text in 3 Schritten',es:'De voz a texto perfecto en 3 pasos',it:'Dalla voce al testo perfetto in 3 passi',zh:'从语音到完美文字只需三步'},
'Blocker:':{fr:'Blocage :',de:'Blockade:',es:'Bloqueo:',it:'Blocco:',zh:'阻塞项：'},
'Session':{fr:'Session',de:'Sitzung',es:'Sesion',it:'Sessione',zh:'会话'},
'1 an':{fr:'1 an',de:'1 Jahr',es:'1 ano',it:'1 anno',zh:'1 年'},
'2 years':{fr:'2 ans',de:'2 Jahre',es:'2 anos',it:'2 anni',zh:'2 年'},
'We implement industry-standard security measures including end-to-end encryption for data in transit, encryption at rest for stored data, and regular security audits. However, no method of electronic storage is 100% secure.':{fr:'Nous mettons en oeuvre des mesures de securite standard incluant le chiffrement de bout en bout. Aucune methode n\'est 100% securisee.',de:'Wir setzen Sicherheitsmassnahmen wie Ende-zu-Ende-Verschlusselung um. Keine Methode ist 100% sicher.',es:'Implementamos medidas de seguridad estandar incluyendo cifrado de extremo a extremo. Ningun metodo es 100% seguro.',it:'Implementiamo misure di sicurezza standard inclusa la crittografia end-to-end. Nessun metodo e sicuro al 100%.',zh:'我们实施行业标准安全措施，包括端到端加密和静态数据加密。但没有任何电子存储方式是 100% 安全的。'},
'Required for the website to function — session management, authentication, security':{fr:'Necessaire au fonctionnement — session, authentification, securite',de:'Erforderlich — Sitzungsverwaltung, Authentifizierung, Sicherheit',es:'Necesario — sesion, autenticacion, seguridad',it:'Necessario — sessione, autenticazione, sicurezza',zh:'网站运行必需 — 会话管理、身份验证、安全'},
'All rights reserved.':{fr:'Tous droits reserves.',de:'Alle Rechte vorbehalten.',es:'Todos los derechos reservados.',it:'Tutti i diritti riservati.',zh:'版权所有。'},
'Email':{fr:'E-mail',de:'E-Mail',es:'Email',it:'Email',zh:'邮件'},
'Priority':{fr:'Prioritaire',de:'Prioritat',es:'Prioritario',it:'Prioritario',zh:'优先'},

// data-t attribute keys (used by pricing page)
'pricing.free':{fr:'Gratuit',de:'Kostenlos',es:'Gratis',it:'Gratuito',zh:'免费版'},
'pricing.free.desc':{fr:'Commencez votre essai gratuit',de:'Kostenlose Testversion',es:'Comienza tu prueba gratuita',it:'Inizia la prova gratuita',zh:'开始免费试用'},
'pricing.prime':{fr:'Premium',de:'Prime',es:'Premium',it:'Premium',zh:'高级版'},
'pricing.prime.desc':{fr:'Tout Gratuit en illimite',de:'Alles Kostenlos unbegrenzt',es:'Todo Gratis ilimitado',it:'Tutto Gratuito illimitato',zh:'免费版全部功能 + 无限使用'},
'pricing.tag':{fr:'Tarifs',de:'Preise',es:'Precios',it:'Prezzi',zh:'定价方案'},
'compare.tag':{fr:'Comparer',de:'Vergleichen',es:'Comparar',it:'Confronta',zh:'方案对比'},
'faq.tag':{fr:'FAQ',de:'FAQ',es:'FAQ',it:'FAQ',zh:'常见问题'},
'pricing.title1':{fr:'Essayez ',de:'Testen Sie ',es:'Pruebalo ',it:'Provalo ',zh:'免费'},
'pricing.title2':{fr:'gratuitement.',de:'kostenlos.',es:'gratis.',it:'gratis.',zh:'试用。'},
'compare.title1':{fr:'Gratuit vs ',de:'Kostenlos vs ',es:'Gratis vs ',it:'Gratuito vs ',zh:'免费版 vs '},
'compare.title2':{fr:'Premium',de:'Prime',es:'Premium',it:'Premium',zh:'高级版'},
'faq.title1':{fr:'Questions ',de:'Haufig ',es:'Preguntas ',it:'Domande ',zh:'常见'},
'faq.title2':{fr:'frequentes',de:'gestellte Fragen',es:'frecuentes',it:'frequenti',zh:'问题解答'},
'For questions about these Terms, contact us at':{fr:'Questions :',de:'Fragen:',es:'Preguntas:',it:'Domande:',zh:'问题联系：'},
// Terms — remaining
'By creating an account or using VoiceNote in any way, you agree to these Terms. If you do not agree, do not use our services.':{fr:'En creant un compte, vous acceptez ces conditions. Sinon, n\'utilisez pas nos services.',de:'Durch Kontoerstellung stimmen Sie zu. Andernfalls nicht nutzen.',es:'Al crear cuenta, aceptas. Si no, no uses nuestros servicios.',it:'Creando un account, accetti. Altrimenti non usare i nostri servizi.',zh:'创建账户即表示同意。如不同意，请勿使用。'},
'You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.':{fr:'Fournissez des informations exactes. Vous etes responsable de la confidentialite de vos identifiants.',de:'Genaue Informationen erforderlich. Sie sind fur die Vertraulichkeit Ihrer Zugangsdaten verantwortlich.',es:'Proporciona informacion precisa. Eres responsable de la confidencialidad.',it:'Fornisci informazioni accurate. Sei responsabile della riservatezza delle credenziali.',zh:'请提供准确信息。你负责保护账户凭证的机密性。'},
'You agree to use VoiceNote only for lawful purposes. You may not:':{fr:'Vous acceptez d\'utiliser VoiceNote uniquement a des fins licites. Vous ne pouvez pas :',de:'Sie stimmen zu, VoiceNote nur rechtmassig zu nutzen. Nicht erlaubt:',es:'Aceptas usar VoiceNote solo para fines licitos. No puedes:',it:'Accetti di usare VoiceNote solo per scopi leciti. Non puoi:',zh:'你同意仅合法使用 VoiceNote。不得：'},
'Use the service to create, store, or distribute illegal content':{fr:'Utiliser le service pour du contenu illegal',de:'Illegale Inhalte erstellen oder verbreiten',es:'Usar el servicio para contenido ilegal',it:'Usare per contenuti illegali',zh:'创建、存储或传播非法内容'},
'Violate any applicable laws or regulations':{fr:'Violer les lois ou reglements applicables',de:'Geltende Gesetze verletzen',es:'Violar leyes aplicables',it:'Violare leggi applicabili',zh:'违反适用法律法规'},
'Attempt to gain unauthorized access to our systems':{fr:'Tenter d\'acceder sans autorisation a nos systemes',de:'Unbefugten Zugriff versuchen',es:'Intentar acceso no autorizado',it:'Tentare accesso non autorizzato',zh:'试图未经授权访问系统'},
'Resell or redistribute the service without authorization':{fr:'Revendre ou redistribuer sans autorisation',de:'Ohne Genehmigung weiterverkaufen',es:'Revender sin autorizacion',it:'Rivendere senza autorizzazione',zh:'未经授权转售或分发'},
'Use the service to harass, abuse, or harm others':{fr:'Utiliser pour harasser ou nuire a autrui',de:'Belastigung oder Schadigung',es:'Usar para acosar o danar',it:'Usare per molestare o danneggiare',zh:'骚扰、虐待或伤害他人'},
'VoiceNote offers both free and paid subscription plans. Paid subscriptions are billed in advance on a monthly or annual basis. All payments are non-refundable except as required by law or as explicitly stated in our refund policy. We offer a 7-day free trial for new Pro and Prime subscribers.':{fr:'VoiceNote propose des abonnements gratuits et payants, factures a l\'avance. Essai gratuit de 7 jours disponible.',de:'VoiceNote bietet Gratis- und Paid-Abos, Vorauszahlung. 7-tagige Testversion verfugbar.',es:'VoiceNote ofrece planes gratis y de pago, facturados por adelantado. Prueba de 7 dias.',it:'VoiceNote offre piani gratis e a pagamento, fatturati in anticipo. Prova di 7 giorni.',zh:'VoiceNote 提供免费和付费方案，预付制。新用户 7 天免费试用。'},
'You retain all rights to the content you create using VoiceNote. We do not claim ownership of your notes or recordings. VoiceNote, its logo, and all related trademarks are our exclusive property.':{fr:'Vous conservez les droits sur votre contenu. VoiceNote et son logo sont notre propriete exclusive.',de:'Sie behalten Rechte an Ihren Inhalten. VoiceNote und Logo sind unser Eigentum.',es:'Conservas los derechos de tu contenido. VoiceNote y su logo son de nuestra propiedad.',it:'Conservi i diritti sui tuoi contenuti. VoiceNote e logo sono di nostra proprieta.',zh:'你保留内容权利。VoiceNote 及其商标是我们的专有财产。'},
'VoiceNote is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including loss of data or profits, to the fullest extent permitted by law.':{fr:'VoiceNote est fourni "tel quel" sans garantie. Nous ne sommes pas responsables des dommages.',de:'VoiceNote wird "wie besehen" bereitgestellt. Keine Haftung fur Schaden.',es:'VoiceNote se proporciona "tal cual". No somos responsables de danos.',it:'VoiceNote e fornito "cosi com\'e". Non siamo responsabili per danni.',zh:'VoiceNote 按"原样"提供。我们不对使用产生的损害承担责任。'},
'We may suspend or terminate your account at any time for violation of these Terms. You may delete your account at any time. Upon termination, your right to use the service will immediately cease.':{fr:'Nous pouvons suspendre votre compte pour violation. Vous pouvez le supprimer a tout moment.',de:'Wir konnen Ihr Konto bei Verstoben sperren. Loschung jederzeit moglich.',es:'Podemos suspender tu cuenta por violacion. Puedes eliminarla cuando quieras.',it:'Possiamo sospendere l\'account per violazione. Puoi eliminarlo in qualsiasi momento.',zh:'我们可因违规暂停账户。你也可以随时删除账户。'},
'We reserve the right to modify these Terms at any time. We will notify users of material changes via email or in-app notification. Continued use after changes constitutes acceptance.':{fr:'Nous nous reservons le droit de modifier ces conditions. Les utilisateurs seront informes des changements importants.',de:'Wir behalten uns Anderungen vor. Benachrichtigung uber wesentliche Anderungen.',es:'Nos reservamos el derecho de modificar. Notificaremos cambios importantes.',it:'Ci riserviamo il diritto di modificare. Informeremo gli utenti dei cambiamenti.',zh:'我们保留修改权利。重大变更将通知用户。继续使用即表示接受。'},
'For questions about these Terms, contact us at':{fr:'Questions sur ces conditions :',de:'Fragen zu diesen Bedingungen:',es:'Preguntas sobre estos terminos:',it:'Domande su questi termini:',zh:'条款问题请联系：'},
// Meta titles & descriptions
'VoiceNote — Speak Naturally, Get Polished Text Instantly':{fr:'VoiceNote — Parlez, obtenez un texte parfait',de:'VoiceNote — Sprechen Sie, erhalten Sie perfekten Text',es:'VoiceNote — Habla, obten texto perfecto',it:'VoiceNote — Parla, ottieni testo perfetto',zh:'VoiceNote — 自然说，获得完美文字'},
'Transform your messy voice notes into clear, structured, and professional text. Perfect for meetings, ideas, emails, and content creation.':{fr:'Transformez vos notes vocales en texte clair et professionnel. Parfait pour reunions, idees, emails et creation de contenu.',de:'Verwandeln Sie Sprachaufnahmen in klaren, strukturierten Text. Perfekt fur Meetings, Ideen, E-Mails.',es:'Transforma tus notas de voz en texto claro y profesional. Perfecto para reuniones, ideas, emails y contenido.',it:'Trasforma le tue note vocali in testo chiaro e professionale. Perfetto per riunioni, idee, email e contenuti.',zh:'把你的语音笔记变成清晰、有条理的专业文字。适用于会议、创意、邮件和内容创作。'},
'Pricing Plans — VoiceNote':{fr:'Tarifs — VoiceNote',de:'Preise — VoiceNote',es:'Precios — VoiceNote',it:'Prezzi — VoiceNote',zh:'定价方案 — VoiceNote'},
'Your first 10 voice notes are free. Upgrade to Prime for unlimited recording and AI polishing.':{fr:'Vos 10 premieres notes vocales sont gratuites. Passez a Prime pour un enregistrement illimite.',de:'Ihre ersten 10 Sprachnotizen sind kostenlos. Upgrade auf Prime fur unbegrenzte Aufnahmen.',es:'Tus primeras 10 notas de voz son gratis. Actualiza a Prime para grabacion ilimitada.',it:'Le tue prime 10 note vocali sono gratis. Passa a Prime per registrazioni illimitate.',zh:'前 10 条语音笔记免费。升级 Prime 解锁无限录音和 AI 润色。'},
'Download VoiceNote — Available on iOS':{fr:'Telecharger VoiceNote — Disponible sur iOS',de:'VoiceNote herunterladen — Verfugbar fur iOS',es:'Descargar VoiceNote — Disponible en iOS',it:'Scarica VoiceNote — Disponibile su iOS',zh:'下载 VoiceNote — 适用于 iOS'},
'Download VoiceNote today. Start turning your spoken thoughts into clear, polished text in seconds.':{fr:'Telechargez VoiceNote. Transformez vos pensees en texte clair en quelques secondes.',de:'Laden Sie VoiceNote herunter. Verwandeln Sie Gedanken in klaren Text.',es:'Descarga VoiceNote. Convierte tus pensamientos en texto claro en segundos.',it:'Scarica VoiceNote. Trasforma i tuoi pensieri in testo chiaro in pochi secondi.',zh:'立即下载 VoiceNote，秒速把语音变成清晰文字。'},
'Contact Us — VoiceNote Help Center':{fr:'Contact — Centre d\'aide VoiceNote',de:'Kontakt — VoiceNote Hilfe',es:'Contacto — Centro de ayuda VoiceNote',it:'Contatto — Centro assistenza VoiceNote',zh:'联系我们 — VoiceNote 帮助中心'},
'Have feedback, questions, or feature requests? Reach out to the VoiceNote team.':{fr:'Commentaires, questions ou suggestions ? Contactez l\'equipe VoiceNote.',de:'Feedback, Fragen oder Funktionswunsche? Kontaktieren Sie das VoiceNote-Team.',es:'Comentarios, preguntas o sugerencias? Contacta al equipo de VoiceNote.',it:'Feedback, domande o richieste? Contatta il team VoiceNote.',zh:'有反馈、问题或功能建议？联系 VoiceNote 团队。'},
'Privacy Policy — VoiceNote':{fr:'Confidentialite — VoiceNote',de:'Datenschutz — VoiceNote',es:'Privacidad — VoiceNote',it:'Privacy — VoiceNote',zh:'隐私政策 — VoiceNote'},
'VoiceNote Privacy Policy — learn how we collect, use, and protect your data.':{fr:'Politique de confidentialite VoiceNote — decouvrez comment nous collectons et protegeons vos donnees.',de:'VoiceNote Datenschutz — erfahren Sie, wie wir Ihre Daten erfassen und schutzen.',es:'Politica de privacidad de VoiceNote — como recopilamos y protegemos tus datos.',it:'Informativa sulla privacy di VoiceNote — come raccogliamo e proteggiamo i tuoi dati.',zh:'VoiceNote 隐私政策 — 了解我们如何收集、使用和保护你的数据。'},
'Terms of Service — VoiceNote':{fr:'Conditions d\'utilisation — VoiceNote',de:'Nutzungsbedingungen — VoiceNote',es:'Terminos de servicio — VoiceNote',it:'Termini di servizio — VoiceNote',zh:'服务条款 — VoiceNote'},
'VoiceNote Terms of Service — the rules and guidelines for using our application.':{fr:'Conditions d\'utilisation VoiceNote — regles et directives pour l\'utilisation de notre application.',de:'VoiceNote Nutzungsbedingungen — Regeln fur die Nutzung unserer App.',es:'Terminos de servicio de VoiceNote — reglas para usar nuestra aplicacion.',it:'Termini di servizio VoiceNote — regole per l\'uso della nostra app.',zh:'VoiceNote 服务条款 — 使用我们应用的规则和指南。'},
'Cookie Policy — VoiceNote':{fr:'Politique de cookies — VoiceNote',de:'Cookie-Richtlinie — VoiceNote',es:'Politica de cookies — VoiceNote',it:'Politica sui cookie — VoiceNote',zh:'Cookie 政策 — VoiceNote'},
'VoiceNote Cookie Policy — understand how we use cookies and similar technologies.':{fr:'Politique de cookies VoiceNote — comprenez comment nous utilisons les cookies.',de:'VoiceNote Cookie-Richtlinie — wie wir Cookies verwenden.',es:'Politica de cookies de VoiceNote — como usamos las cookies.',it:'Politica sui cookie VoiceNote — come usiamo i cookie.',zh:'VoiceNote Cookie 政策 — 了解我们如何使用 Cookie 及类似技术。'},
};
function getLang(){var s=localStorage.getItem(LANG_KEY);return s&&LANGS.indexOf(s)>=0?s:(LANGS.indexOf(navigator.language.slice(0,2))>=0?navigator.language.slice(0,2):'en');}
var _enTexts=null;
function cacheEN(){if(_enTexts)return;_enTexts=[];document.querySelectorAll('[data-t]').forEach(function(el){_enTexts.push({el:el,text:el.textContent});});}
function restoreEN(){if(!_enTexts)return;_enTexts.forEach(function(item){item.el.textContent=item.text;});_enTexts=null;}
function setLang(l){if(LANGS.indexOf(l)<0)return;localStorage.setItem(LANG_KEY,l);var url=l==='en'?'/':'/'+l+'/';history.pushState(null,'',url);if(l==='en'){restoreEN();}else{cacheEN();applyLang();}updateBadge();document.getElementById('langDropdown').classList.add('hidden');}
function applyLang(){
  var lang=getLang();if(lang==='en')return;
  document.documentElement.lang=lang;
  // Translate meta
  var dt=document.title;if(T[dt]&&T[dt][lang])document.title=T[dt][lang];
  var md=document.querySelector('meta[name="description"]');if(md){var dc=md.getAttribute('content');if(T[dc]&&T[dc][lang])md.setAttribute('content',T[dc][lang]);}
  var i,el,t,tag;
  // Leaf elements
  var all=document.querySelectorAll('p,span,h1,h2,h3,h4,h5,h6,li,a,button,td,th,label,div');
  for(i=0;i<all.length;i++){el=all[i];if(el.children.length>0)continue;if(el.closest&&el.closest('#langSwitcher'))continue;tag=el.tagName;if(tag==='SCRIPT'||tag==='STYLE'||tag==='NOSCRIPT'||tag==='INPUT'||tag==='TEXTAREA')continue;t=el.textContent.trim();if(!t||t.length<2)continue;if(T[t]&&T[t][lang])el.textContent=T[t][lang];}
  // Text nodes for fragmented content
  var walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,null,false);
  var nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
  for(i=0;i<nodes.length;i++){var node=nodes[i];var p=node.parentElement;if(!p||p.tagName==='SCRIPT'||p.tagName==='STYLE'||p.tagName==='NOSCRIPT')continue;if(p.closest&&p.closest('#langSwitcher'))continue;t=node.textContent.trim();if(!t||t.length<2)continue;if(T[t]&&T[t][lang])node.textContent=T[t][lang];}
  // Step 3: data-t attributes (leaf elements only, preserves gradient spans)
  var dts=document.querySelectorAll('[data-t]');
  for(i=0;i<dts.length;i++){var dt=dts[i];if(dt.children.length>0)continue;if(dt.closest&&dt.closest('#langSwitcher'))continue;var key=dt.getAttribute('data-t');if(T[key]&&T[key][lang])dt.textContent=T[key][lang];}
}

document.addEventListener('DOMContentLoaded',function(){
  var names={en:'English',fr:'Francais',de:'Deutsch',es:'Espanol',it:'Italiano',zh:'中文'};
  var shorts={en:'EN',fr:'FR',de:'DE',es:'ES',it:'IT',zh:'中文'};
  var l=getLang();
  var w=document.getElementById('langSwitcher');
  if(!w)return;
  w.innerHTML='';
  var c=document.createElement('span');c.id='langCurrent';
  c.className='text-xs font-medium text-gray-500 cursor-pointer hover:text-gray-700 flex items-center gap-1';
  c.innerHTML=shorts[l]+' <svg class="h-3 w-3" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><polyline points="6 9 12 15 18 9"/></svg>';
  w.appendChild(c);
  var d=document.createElement('div');d.id='langDropdown';
  d.className='absolute top-full right-0 mt-1 bg-white border border-gray-100 rounded-xl shadow-lg py-1 hidden z-50 min-w-[140px]';
  for(var i=0;i<LANGS.length;i++){(function(x){var o=document.createElement('button');o.textContent=names[x];
    o.className='lang-option block w-full text-left px-4 py-2 text-sm text-gray-600 hover:bg-gray-50 '+(x===l?'font-semibold text-brand-600':'');
    o.onclick=function(){setLang(x);d.classList.add('hidden');};d.appendChild(o);})(LANGS[i]);}
  w.appendChild(d);
  c.addEventListener('click',function(e){e.stopPropagation();d.classList.toggle('hidden');});
  document.addEventListener('click',function(){d.classList.add('hidden');});
  if(l!=='en')applyLang();
});
